export default {
  id: "git",
  n: 13,
  part: "C",
  title: "Git for real",
  hook: "Git is four object types and a folder of pointers. Learn that and no command can scare you again.",
  minutes: 70,
  levels: ["use", "understand", "rebuild"],
  sections: [
    {
      title: "Git is a key-value store",
      beats: [
        { t: "say", x: "Forget branches for a minute. Under everything, git is a **content-addressed store**: you hand it bytes, it hands back the SHA-1 of those bytes, and that hash is the key forever." },
        {
          t: "code",
          lang: "bash",
          src: "$ echo hello | git hash-object --stdin\nce013625030ba8dba906f756967f9e9ca394464a\n\n# same bytes on any machine, any year: same key\n$ printf 'blob 6\\0hello\\n' | sha1sum\nce013625030ba8dba906f756967f9e9ca394464a  -\n\n$ git cat-file -p ce0136\nhello",
          mark: [2, 6],
          note: "The key is `sha1(\"blob \" + size + \"\\0\" + content)`. No file name, no date. The name lives somewhere else.",
        },
        {
          t: "predict",
          lang: "bash",
          src: "# fresh repo\necho hello > a.txt\nmkdir docs && echo hello > docs/copy.txt\ngit add .\ngit count-objects -v | grep count",
          q: "How many blob objects did `git add` write?",
          options: ["2, one per file", "1", "0, blobs are written on commit", "3, including one for the folder"],
          answer: 1,
          why: "Same bytes, same hash, same object. Git stores it once. The folder becomes a **tree** later, at commit time. And `add` does write blobs right away, which matters when you need to recover work.",
        },
        {
          t: "table",
          head: ["Object", "Holds", "Points to"],
          rows: [
            ["blob", "Raw file bytes. No name, no mode", "nothing"],
            ["tree", "Lines of `mode type sha name`, one per entry", "blobs and other trees"],
            ["commit", "tree, parent(s), author, committer, message", "one tree, 0+ parent commits"],
            ["tag (annotated)", "object, tagger, message, optional signature", "any object, usually a commit"],
          ],
          caption: "The entire data model. Everything else is refs and tooling.",
        },
        {
          t: "viz",
          name: "frames",
          props: {
            cols: ["Working tree", "Index", ".git/objects", "Refs"],
            frames: [
              { cells: [[], [], [], ["HEAD: ref: refs/heads/main", "main: (unborn)"]], note: "`git init`. HEAD already names main, but main doesn't exist yet. That's an unborn branch." },
              { cells: [["a.txt: hello"], [], [], ["HEAD: ref: refs/heads/main", "main: (unborn)"]], note: "`echo hello > a.txt`. The file exists only in your folder. Git knows nothing." },
              { cells: [["a.txt: hello"], ["a.txt -> ce0136"], ["blob ce0136"], ["HEAD: ref: refs/heads/main", "main: (unborn)"]], note: "`git add a.txt` hashes the bytes, writes the blob, records path -> SHA in the index. No commit yet." },
              { cells: [["a.txt: hello"], ["a.txt -> ce0136"], ["blob ce0136", "tree 2e8117 {a.txt}", "commit C1 {tree 2e8117}"], ["HEAD: ref: refs/heads/main", "main: C1"]], note: "`git commit` turns the index into a tree, wraps it in a commit, then writes one ref. Three objects, one tiny file." },
              { cells: [["a.txt: hello", "b.txt: hi"], ["a.txt -> ce0136", "b.txt -> 45b983"], ["blob ce0136", "tree 2e8117", "commit C1", "blob 45b983", "tree e51706 {a, b}", "commit C2 {parent C1}"], ["HEAD: ref: refs/heads/main", "main: C2"]], note: "Add and commit b.txt. The new tree reuses blob ce0136. Unchanged files cost zero bytes." },
              { cells: [["a.txt: hello", "b.txt: hi"], ["a.txt -> ce0136", "b.txt -> 45b983"], ["blob ce0136", "tree 2e8117", "commit C1", "blob 45b983", "tree e51706", "commit C2"], ["HEAD: ref: refs/heads/main", "main: C2", "feat: C2"]], note: "`git branch feat` writes a 41-byte file holding C2. No files copied. That's why branching is free." },
              { cells: [["a.txt: hello world", "b.txt: hi"], ["a.txt -> 3b18e5", "b.txt -> 45b983"], ["...", "blob 3b18e5", "tree 5328a1", "commit C3 {parent C2}"], ["HEAD: ref: refs/heads/feat", "main: C2", "feat: C3"]], note: "`git switch feat`, edit, commit. HEAD now names feat, so feat moves. main stays at C2." },
            ],
          },
        },
        {
          t: "pitfall",
          h: "Git stores snapshots, not diffs",
          x: "Every commit points at a full tree. Diffs are computed on demand, which is why rename detection is a guess (50% similarity by default) made at diff time. Packfiles delta-compress later, but that's storage, not the model.",
        },
        {
          t: "quiz",
          q: "You change one byte in `src/app/deep/file.js` and commit. Which new objects appear?",
          options: ["One blob", "One blob and one tree", "One blob, a tree for every folder on the path up to root, one commit", "A full copy of every file"],
          answer: 2,
          why: "A tree's hash depends on its children's hashes. Change a leaf and every ancestor tree gets a new SHA, like a Merkle tree. Sibling folders are reused untouched.",
        },
      ],
    },
    {
      title: "Three trees: HEAD, index, working",
      beats: [
        { t: "say", x: "There are always three versions of every file: the one in the last commit (**HEAD**), the one staged for the next commit (the **index**), and the one on disk. Almost every command moves content between these three." },
        {
          t: "predict",
          lang: "bash",
          src: "echo v1 > f.txt\ngit add f.txt\necho v2 > f.txt\ngit commit -m \"save\"\ngit show HEAD:f.txt",
          q: "What does the commit contain?",
          options: ["v2", "v1", "Nothing, the add was cancelled", "Both, as a conflict"],
          answer: 1,
          why: "`add` copies content into the index *at that moment*. The commit is built from the index, not your disk. `git status` will still show f.txt modified: v2 is only on disk.",
        },
        {
          t: "table",
          head: ["Command", "Compares"],
          rows: [
            ["`git diff`", "working tree vs index (what you haven't staged)"],
            ["`git diff --staged`", "index vs HEAD (what the next commit will contain)"],
            ["`git diff HEAD`", "working tree vs HEAD (everything since the last commit)"],
            ["`git restore f`", "copy index -> working (discard unstaged edits)"],
            ["`git restore --staged f`", "copy HEAD -> index (unstage, keep your edits)"],
          ],
        },
        { t: "say", x: "The index is a real binary file, `.git/index`. Besides path and SHA it caches each file's size and mtime, so `git status` can skip hashing files whose stat didn't change. That's how it stays fast on 100k-file repos." },
        {
          t: "code",
          lang: "text",
          src: "$ git add -p\ndiff --git a/api.js b/api.js\n@@ -10,6 +10,7 @@\n   const res = await fetch(url);\n+  console.log('DEBUG', res.status);\n   if (!res.ok) throw new HttpError(res);\n(1/3) Stage this hunk [y,n,q,a,d,s,e,?]? n",
          mark: [7],
          note: "`y` stage, `n` skip, `s` split the hunk smaller, `e` edit the patch by hand. Same `-p` works on `restore`, `reset` and `stash`.",
        },
        {
          t: "pitfall",
          h: "`git add .` is how debug logs get shipped",
          x: "Staging everything means committing everything, including the `console.log` and the half-finished refactor. `git add -p` makes you read your own diff hunk by hunk. It's the cheapest code review you'll ever get.",
        },
      ],
    },
    {
      title: "HEAD, refs and branches",
      beats: [
        {
          t: "code",
          lang: "bash",
          src: "$ cat .git/HEAD\nref: refs/heads/main\n\n$ cat .git/refs/heads/main\n9f2c1e04b7a3d8e6f5c2a1b0e9d8c7b6a5f4e3d2\n\n$ git switch --detach HEAD~1\n$ cat .git/HEAD\n4a1b2c3d5e6f708192a3b4c5d6e7f8091a2b3c4d",
          note: "HEAD normally names a branch. Detached, it holds a SHA directly. Refs may also sit in `.git/packed-refs`; use `git rev-parse` rather than cat in scripts.",
        },
        { t: "say", x: "A **branch** is a file holding one SHA. Committing on a branch means: write the commit, then overwrite that file with the new SHA. That's all. Type commands below: `commit`, `branch x`, `switch x`." },
        { t: "viz", name: "gitgraph", props: { setup: ["commit", "commit", "branch feat", "switch feat", "commit", "switch main", "commit"] } },
        {
          t: "predict",
          lang: "bash",
          src: "git switch --detach v1.0\n# fix a bug, then\ngit commit -am \"hotfix\"\ngit switch main",
          q: "Where does the hotfix commit live now?",
          options: ["On main", "On a new branch named v1.0", "Nowhere named; only the reflog still points at it", "It was deleted when you switched"],
          answer: 2,
          why: "Detached commits moved only HEAD. When HEAD leaves, nothing names them. Git warns and prints the SHA; `git branch hotfix <sha>` saves it. Ignore that and gc prunes it after the reflog expires.",
        },
        {
          t: "quiz",
          q: "On a merge commit, what's the difference between `HEAD~2` and `HEAD^2`?",
          options: ["None", "`~2` is two steps up the first-parent line; `^2` is the second parent", "`^2` is the grandparent; `~2` is the second parent", "`^2` only works on tags"],
          answer: 1,
          why: "`~n` walks first parents n times. `^n` picks the n-th parent of one commit. `HEAD^2` on a merge is the tip of the branch that was merged in. `HEAD~` and `HEAD^` are the same commit.",
        },
        {
          t: "pitfall",
          h: "Deleting a branch deletes nothing",
          x: "`git branch -D feat` removes one 41-byte file. The commits stay in the object store until gc, and the reflog keeps them reachable for 30 days by default. Panic is almost never warranted in git; see the reflog section.",
        },
      ],
    },
    {
      title: "Merge vs rebase",
      beats: [
        { t: "say", h: "Fast-forward", x: "If main hasn't moved since you branched, main is an ancestor of feat. Merging just slides the main pointer forward. No new commit. Try `merge feat` below." },
        { t: "viz", name: "gitgraph", props: { setup: ["commit", "branch feat", "switch feat", "commit", "commit", "switch main"] } },
        { t: "say", h: "Three-way merge", x: "If both moved, git finds the **merge base**, the best common ancestor (`git merge-base main feat`), diffs base->ours and base->theirs, and combines them. The result is a commit with two parents." },
        { t: "viz", name: "gitgraph", props: { setup: ["commit", "commit", "branch feat", "switch feat", "commit", "commit", "switch main", "commit", "merge feat"] } },
        { t: "say", h: "Rebase", x: "Rebase takes your commits since the merge base and replays each one as a new commit on top of the target. Same diffs, new parents, so **new SHAs**. The old commits still exist; nothing names them anymore. Type `rebase main`." },
        { t: "viz", name: "gitgraph", props: { setup: ["commit", "commit", "branch feat", "switch feat", "commit", "commit", "switch main", "commit", "switch feat"] } },
        {
          t: "predict",
          lang: "bash",
          src: "git log --format=%h main..feat   # a1b2c3d e4f5a6b 0c9d8e7\ngit rebase main                  # main had 2 new commits\ngit log --format=%h main..feat",
          q: "How many of the three SHAs survive?",
          options: ["All three, content didn't change", "Only the first", "None", "Only the last"],
          answer: 2,
          why: "A commit's hash covers its parent's hash. Change the first commit's parent and its SHA changes, which changes the second's parent, and so on down the chain. Rebase rewrites every replayed commit.",
        },
        {
          t: "compare",
          a: { label: "merge", lang: "text", src: "*   Merge branch 'feat'\n|\\\n| * feat: add cache\n| * feat: add api\n* | main: fix typo\n|/\n* base" },
          b: { label: "rebase, then fast-forward", lang: "text", src: "* feat: add cache\n* feat: add api\n* main: fix typo\n* base" },
          x: "Merge keeps true history and never rewrites. Rebase gives a straight line that bisects and reads cleanly, at the cost of new SHAs. Most teams: rebase your own branch, merge into shared ones.",
        },
        {
          t: "pitfall",
          h: "Never rebase commits someone else has",
          x: "If a teammate built on your old SHAs, your rebase forks history: they now have commits that look like yours but aren't. Their next pull duplicates everything. Rebase freely until you push to a shared branch, then stop.",
        },
        {
          t: "code",
          lang: "bash",
          src: "# found a bug in commit 3a4b5c6 of your branch\ngit commit --fixup=3a4b5c6\n\n# later: fold every fixup into its target, automatically\ngit rebase -i --autosquash main\n\n# make it the default\ngit config --global rebase.autoSquash true\ngit config --global rebase.updateRefs true  # move stacked branches too",
          note: "Fixup commits keep review diffs small; autosquash cleans up before merge. `updateRefs` (git 2.38+) drags branches stacked on this one along with the rebase.",
        },
      ],
    },
    {
      title: "Reading conflicts",
      beats: [
        {
          t: "code",
          lang: "text",
          file: "f.txt, during git merge feat",
          src: "<<<<<<< HEAD\ntimeout = 5000\n||||||| 1294280\ntimeout = 3000\n=======\ntimeout = 3000\nretries = 2\n>>>>>>> feat",
          mark: [3, 4],
          note: "Top: ours. Bottom: theirs. Middle: the merge base, which is only shown with `zdiff3`. Now you can see main changed the timeout and feat added retries: keep both.",
        },
        { t: "say", x: "Without the base section you're guessing who changed what. With it, a conflict becomes two readable diffs. This one config line removes most conflict pain:" },
        {
          t: "code",
          lang: "bash",
          src: "git config --global merge.conflictStyle zdiff3\ngit config --global rerere.enabled true   # remember resolutions, replay them",
          note: "`rerere` records how you resolved a conflict and reapplies it the next time the same hunks collide, which happens constantly when rebasing a long branch.",
        },
        {
          t: "pitfall",
          h: "During rebase, ours and theirs flip",
          x: "Rebase checks out the target and replays your commits onto it. So `HEAD`/ours is **main**, and theirs is **your** commit. `git checkout --ours` during a rebase throws away your change. Read the marker labels, not your intuition.",
        },
        {
          t: "quiz",
          q: "Mid-rebase you hit a conflict and it's going badly. Safest move?",
          options: ["`git reset --hard`", "`git rebase --abort`", "Delete the branch and start over", "`git push --force` and fix it later"],
          answer: 1,
          why: "`--abort` restores the branch and working tree to exactly where you were before the rebase. `merge --abort` does the same for merges. Both are free; use them without shame.",
        },
      ],
    },
    {
      title: "Undo: reset, revert, reflog",
      beats: [
        {
          t: "table",
          head: ["Command", "Moves branch", "Resets index", "Resets working tree"],
          rows: [
            ["`reset --soft X`", "yes", "no", "no"],
            ["`reset --mixed X` (default)", "yes", "yes", "no"],
            ["`reset --hard X`", "yes", "yes", "yes: uncommitted edits are gone"],
          ],
          caption: "Reset moves the branch HEAD names to X, then optionally copies X into the other two trees.",
        },
        {
          t: "predict",
          lang: "bash",
          src: "# last 3 commits are messy WIP\ngit reset --soft HEAD~3\ngit status --short",
          q: "What does status show?",
          options: ["Nothing, the work is gone", "All changes from the 3 commits, staged", "All changes, unstaged", "A conflict"],
          answer: 1,
          why: "`--soft` moved only the branch. The index still holds the newest tree, so it differs from HEAD by exactly those 3 commits. `git commit` now squashes them into one. The fastest squash there is.",
        },
        { t: "say", x: "`git revert X` is the opposite approach: it makes a **new** commit whose diff undoes X. History only grows, so it's safe on shared branches. Reset rewrites; revert appends. Try both below." },
        { t: "viz", name: "gitgraph", props: { setup: ["commit", "commit", "commit", "commit"] } },
        {
          t: "pitfall",
          h: "Reverting a merge poisons the re-merge",
          x: "Revert a merge (`git revert -m 1 M`) and its commits are still ancestors of main. Merge the fixed branch later and git brings only the *new* commits; the reverted work stays gone. Revert the revert first.",
        },
        {
          t: "code",
          lang: "bash",
          src: "$ git reset --hard HEAD~5          # oops\n$ git reflog\n3f1c2d0 HEAD@{0}: reset: moving to HEAD~5\n9a8b7c6 HEAD@{1}: commit: add search\n5e4d3c2 HEAD@{2}: commit: add filters\n\n$ git reset --hard HEAD@{1}        # back, all five commits\n$ git log -g main --since=yesterday # reflog of one branch",
          mark: [7],
          note: "The reflog records every value HEAD and each branch ever had, locally, for 90 days (30 for unreachable commits). `ORIG_HEAD` also holds the pre-reset/rebase/merge tip.",
        },
        {
          t: "pitfall",
          h: "Staged but lost is recoverable",
          x: "`reset --hard` kills uncommitted work, and the reflog can't help: it only tracks commits. But anything you ever `git add`ed was written as a blob. `git fsck --lost-found` lists dangling blobs; `git show <sha>` reads them back.",
        },
        {
          t: "quiz",
          q: "A bad commit is on `main`, pushed an hour ago, and three people have pulled. Undo it how?",
          options: ["`git reset --hard HEAD~1` and force-push", "`git revert <sha>` and push", "Amend the commit", "Delete main and recreate it"],
          answer: 1,
          why: "Everyone who pulled has the bad commit as an ancestor. A reset + force-push leaves their clones diverged. Revert is a normal commit they pull like any other.",
        },
      ],
    },
    {
      title: "Power tools",
      beats: [
        {
          t: "code",
          lang: "bash",
          src: "# take one fix from a feature branch onto the release branch\ngit switch release-2.3\ngit cherry-pick -x 7c1d2e3\n# message gets: (cherry picked from commit 7c1d2e3...)\n\n# park dirty work, including untracked files\ngit stash push -u -m \"half-done filters\"\ngit stash list\ngit stash pop    # on conflict, the stash is kept, not dropped",
          note: "`cherry-pick` reapplies one commit's diff as a new commit: new SHA, same author. `-x` leaves a trail so you can tell later that two commits are the same fix.",
        },
        {
          t: "pitfall",
          h: "The stash is not a place to keep work",
          x: "Stashes are commits hanging off `refs/stash`, easy to forget and easy to `drop`. Anything you'll need tomorrow deserves a branch: `git switch -c wip/filters && git commit -am wip`. Branches have names; stashes have numbers that shift.",
        },
        { t: "say", h: "bisect", x: "A bug exists now and didn't in v1.4, 1,000 commits ago. `git bisect` checks out the midpoint, you say good or bad, it halves the range. It's binary search over history, and it can run your test for you." },
        {
          t: "predict",
          lang: "bash",
          src: "git bisect start\ngit bisect bad HEAD\ngit bisect good v1.4    # 1000 commits apart\ngit bisect run npm test",
          q: "Roughly how many times does it run the tests?",
          options: ["1000", "500", "About 10", "About 32"],
          answer: 2,
          why: "ceil(log2 1000) = 10. Exit code 0 means good, 125 means skip (can't build this one), 1-127 means bad. A flaky test turns this into garbage, so make the script deterministic first.",
        },
        {
          t: "code",
          lang: "bash",
          file: "bisect.sh",
          src: "#!/bin/sh\nnpm ci --silent || exit 125       # can't even install: skip commit\nnode scripts/repro.mjs            # exits 1 when the bug shows\n\n# git bisect run ./bisect.sh\n# git bisect reset                # back to where you started",
          note: "Write the smallest repro script you can, not the whole test suite. `git bisect start --first-parent` skips commits inside merged branches.",
        },
        {
          t: "quiz",
          q: "You cherry-pick commit C onto `release`, then later merge `main` (which contains C) into `release`. What happens?",
          options: ["Guaranteed conflict", "Usually a clean merge: both sides made the identical change", "C gets applied twice", "Git refuses the merge"],
          answer: 1,
          why: "Three-way merge sees the same hunk on both sides and takes it once. Conflicts only appear if C's lines were later changed on one side. That's also why cherry-picking often is survivable but noisy.",
        },
      ],
    },
    {
      title: "Sharing without breaking things",
      beats: [
        {
          t: "compare",
          a: { label: "--force", lang: "bash", src: "git push --force\n# overwrites origin/feat with yours,\n# whatever a teammate pushed an hour ago" },
          b: { label: "--force-with-lease", lang: "bash", src: "git push --force-with-lease --force-if-includes\n# refuses unless origin/feat is still\n# where you last saw it" },
          x: "The lease is your remote-tracking ref. If the server moved since your last fetch, the push fails instead of silently deleting someone's commits.",
        },
        {
          t: "pitfall",
          h: "Auto-fetch quietly breaks the lease",
          x: "Editors that run `git fetch` in the background update your remote-tracking ref, so the lease matches and the force goes through over commits you've never seen. `--force-if-includes` (git 2.30+) also checks you actually integrated them.",
        },
        {
          t: "pitfall",
          h: "Force-pushing doesn't unpublish",
          x: "Rewrite a commit away and it's gone from the branch, not from the host. Hosts keep objects reachable by SHA URL for a long time, forks share them, and contributor lists update lazily. Leaked a secret? Rotate it. History surgery is cleanup, not a fix.",
        },
        {
          t: "table",
          head: ["File", "Controls", "Travels with repo"],
          rows: [
            ["`.gitignore`", "Which **untracked** files git offers to add", "yes"],
            ["`.git/info/exclude`", "Same, just for you (editor junk)", "no"],
            ["`.gitattributes`", "How files are treated: line endings, binary, diff, merge", "yes"],
          ],
        },
        {
          t: "predict",
          lang: "bash",
          src: "git add config.local.json && git commit -m \"oops\"\necho config.local.json >> .gitignore\necho '{\"key\":2}' > config.local.json\ngit status --short",
          q: "What does status show?",
          options: ["Nothing, it's ignored now", " M config.local.json", "?? config.local.json", "An error"],
          answer: 1,
          why: "`.gitignore` only affects untracked files. Once tracked, always tracked. `git rm --cached config.local.json` untracks it; `git check-ignore -v path` tells you which rule matches anything.",
        },
        {
          t: "code",
          lang: "text",
          file: ".gitattributes",
          src: "* text=auto eol=lf\n*.bat text eol=crlf\n*.png binary\n*.woff2 binary\npackage-lock.json -diff linguist-generated\n\n# after adding this to an existing repo:\n# git add --renormalize . && git commit -m \"normalize line endings\"",
          note: "`text=auto` normalizes to LF in the repo; `eol=lf` also checks out LF on Windows. `-diff` stops 3,000-line lockfile diffs in your terminal.",
        },
        {
          t: "pitfall",
          h: "Line endings: the whole-file diff",
          x: "One Windows dev with `core.autocrlf` off commits CRLF, and every line of the file shows as changed. Blame breaks, merges conflict everywhere. `.gitattributes` wins over everyone's personal config, so fix it in the repo, not in a wiki page.",
        },
        {
          t: "quiz",
          q: "You run `git tag v2.0` then `git push`. What's on the server?",
          options: ["The commits and the tag", "The commits only", "The tag only", "Nothing"],
          answer: 1,
          why: "Plain `push` doesn't send tags. `git tag -a v2.0 -m ...` makes an annotated tag (a real object with tagger and message); `git push --follow-tags` sends annotated tags on pushed commits. Never move a published tag: clones won't refetch it.",
        },
      ],
    },
    {
      title: "Rebuild: git in 60 lines",
      beats: [
        {
          t: "rebuild",
          h: "A content-addressed mini git",
          x: "Objects are strings stored in a Map under their own hash. Trees list blobs, commits name a tree and a parent, refs are plain strings, HEAD is either `ref: ...` or a raw hash. Run it, then read `log` and the object count.",
          mode: "js",
          js: "// A tiny git. Objects live in a Map keyed by the hash of their content.\nconst hash = (s) => {                       // FNV-1a, 32 bits (real git: SHA-1)\n  let h = 0x811c9dc5;\n  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 0x01000193) >>> 0;\n  return h.toString(16).padStart(8, \"0\");\n};\nconst objects = new Map();                  // sha -> \"type\\nbody\"\nconst refs = {};                            // \"refs/heads/main\" -> sha\nlet HEAD = \"ref: refs/heads/main\";\nlet work = {};                              // the working tree: path -> content\nconst put = (type, body) => { const raw = type + \"\\n\" + body, sha = hash(raw); objects.set(sha, raw); return sha; };\nconst get = (sha) => { const raw = objects.get(sha), i = raw.indexOf(\"\\n\"); return { type: raw.slice(0, i), body: raw.slice(i + 1) }; };\nconst headRef = () => (HEAD.startsWith(\"ref: \") ? HEAD.slice(5) : null);\nconst resolve = () => (headRef() ? refs[headRef()] : HEAD);\n\nfunction writeTree() {\n  const lines = Object.keys(work).sort().map((p) => `blob ${put(\"blob\", work[p])} ${p}`);\n  return put(\"tree\", lines.join(\"\\n\"));\n}\nfunction parse(sha) {\n  const [head, msg] = get(sha).body.split(\"\\n\\n\");\n  const c = { tree: null, parents: [], msg };\n  for (const line of head.split(\"\\n\")) {\n    const [k, v] = line.split(\" \");\n    if (k === \"tree\") c.tree = v; else c.parents.push(v);\n  }\n  return c;\n}\nfunction commit(msg) {\n  const parent = resolve();\n  const sha = put(\"commit\", `tree ${writeTree()}\\n${parent ? `parent ${parent}\\n` : \"\"}\\n${msg}`);\n  if (headRef()) refs[headRef()] = sha; else HEAD = sha;   // detached: move HEAD itself\n  return sha;\n}\nconst branch = (name) => { refs[\"refs/heads/\" + name] = resolve(); };\nfunction checkout(target) {\n  const ref = \"refs/heads/\" + target;\n  HEAD = ref in refs ? \"ref: \" + ref : target;              // not a branch? detach\n  work = {};\n  for (const line of get(parse(resolve()).tree).body.split(\"\\n\")) {\n    if (!line) continue;\n    const [, blob, path] = line.split(\" \");\n    work[path] = get(blob).body;\n  }\n}\nfunction log() {\n  for (let sha = resolve(); sha; sha = parse(sha).parents[0]) console.log(sha, parse(sha).msg);\n}\n\nwork[\"a.txt\"] = \"hello\";\ncommit(\"first\");\nwork[\"b.txt\"] = \"world\";\ncommit(\"second\");\nbranch(\"feat\");\ncheckout(\"feat\");\nwork[\"a.txt\"] = \"hello from feat\";\ncommit(\"feat work\");\ncheckout(\"main\");\nlog();\nconsole.log(work, objects.size, \"objects\", Object.keys(refs));",
          task: "Count the objects by hand first: why 9? Then add `mergeBase(a, b)` and a `merge(name)` that fast-forwards when the current tip is an ancestor, else writes a two-parent commit.",
        },
        {
          t: "quiz",
          q: "In the mini git, you commit twice in a row with no changes and the same message. What happens?",
          options: ["Two commits with the same hash", "Two different commits, because the parent differs", "An error", "The second overwrites the first file"],
          answer: 1,
          why: "The second commit's body includes `parent <first>`, so its bytes differ and so does its hash. Real git also hashes author and committer timestamps, which is why the same change at a different second gets a different SHA.",
        },
        {
          t: "mission",
          h: "The break-and-recover drill",
          x: "In a scratch repo: make 6 commits, `reset --hard HEAD~4`, recover them with the reflog. Detach HEAD, commit, switch away, rescue that commit into a branch. Then squash the last 3 commits with `reset --soft`. No searching allowed.",
          hint: "`git reflog` shows every past tip. `git branch rescue <sha>` names a lost commit. `reset --soft` leaves everything staged for one new commit.",
          solution: { lang: "bash", src: "git init -q -b main drill && cd drill\nfor i in 1 2 3 4 5 6; do echo $i >> f; git add f; git commit -qm \"c$i\"; done\ngit reset --hard HEAD~4\ngit reset --hard HEAD@{1}\n\ngit switch --detach HEAD~1 && echo x >> f && git commit -qam lost\ngit switch main   # prints the SHA of 'lost'\ngit branch rescue HEAD@{1}\n\ngit reset --soft HEAD~3 && git commit -m \"c4-c6 squashed\"" },
        },
      ],
    },
  ],
  nobodyTells: [
    "Set `merge.conflictStyle zdiff3` today. Seeing the merge base in every conflict halves the time it takes to resolve one.",
    "`git reset --soft HEAD~n && git commit` is the fastest squash in git. No interactive rebase needed.",
    "Nothing committed is lost for 30 days. `git reflog` first, panic later.",
    "`git log --oneline --graph --all` answers most 'where am I' questions. Alias it.",
    "`git switch -` jumps back to the previous branch, like `cd -`.",
    "Leaked a secret in a commit? Rotate the secret first. Rewriting history doesn't unpublish anything.",
    "`git blame -w -C -C -C` ignores whitespace and follows code moved between files; plain blame often names the person who reformatted.",
    "Add a `.git-blame-ignore-revs` file listing formatting commits and set `blame.ignoreRevsFile` to it; blame skips them.",
  ],
  glossary: [
    ["blob", "An object holding raw file bytes, keyed by the SHA of its content. No name, no mode."],
    ["tree", "An object listing names, modes and SHAs of blobs and subtrees: one directory snapshot."],
    ["index", "The staging area, `.git/index`: the tree your next commit will be built from."],
    ["ref", "A name that holds a SHA: branches, tags, remote-tracking branches."],
    ["HEAD", "What you have checked out: normally a branch name, a raw SHA when detached."],
    ["merge base", "The best common ancestor of two commits; the 'before' in a three-way merge."],
    ["fast-forward", "Moving a branch pointer ahead along existing history, with no new commit."],
    ["reflog", "A local log of every value HEAD and each branch had. Your undo history."],
    ["force-with-lease", "Force-push that only succeeds if the remote ref is still where you last saw it."],
  ],
  explain: "Explain to a friend what a git branch physically is, and why rebasing changes commit SHAs while merging doesn't.",
};
