export default {
  id: "seeing",
  n: 34,
  part: "G",
  title: "Seeing like a designer",
  hook: "Design isn't taste. It's a ranking problem with five levers, and you can test every answer by squinting.",
  minutes: 60,
  levels: ["use", "understand", "rebuild"],
  sections: [
    {
      title: "Hierarchy is a ranking",
      beats: [
        { t: "say", x: "Every screen answers one question: what does the eye hit first, second, third. That order is **visual hierarchy**. Get it wrong and the UI reads like a ransom note: everything shouting, nothing heard." },
        {
          t: "table",
          head: ["Lever", "Raises rank by", "Overused, it looks like"],
          rows: [
            ["Size", "Bigger reads first, but only once it's clearly bigger (~1.25x or more)", "Three headlines fighting for first place"],
            ["Weight", "Bold pulls the eye without taking more room", "Bold everywhere, so bold means nothing"],
            ["Colour and contrast", "More contrast with the page wins; saturation wins among equals", "A rainbow of 'important' badges"],
            ["Space", "Isolation: the thing with room around it matters", "Airless screens where nothing stands out"],
            ["Position", "Top and start edge get read first (left, in LTR languages)", "The key action buried bottom-right of a long form"],
          ],
          caption: "Five levers. Pull two or three at once for the top rank, none for the bottom.",
        },
        {
          t: "predict",
          lang: "html",
          src: "<div class=\"card\">\n  <p class=\"label\">Monthly total</p>\n  <p class=\"value\">$48.00</p>\n  <p class=\"note\">Billed on the 1st.</p>\n</div>\n\n<style>\n  .label { font: 600 20px system-ui; color: #111; }\n  .value { font: 400 20px system-ui; color: #888; }\n  .note  { font: 400 14px system-ui; color: #111; }\n</style>",
          q: "The number is the point of this card. What's wrong with the ranking?",
          options: ["Nothing, it's fine", "The label outranks the value it describes", "The note should be bigger", "It needs a border"],
          answer: 1,
          why: "Labels are metadata. Here the label is darker and bolder than the number, so the eye lands on the word 'total'. Flip it: value big and dark, label small and muted. People scan for data, not for captions.",
        },
        { t: "say", h: "Emphasise by de-emphasising", x: "When everything feels equal, don't make the important thing louder. Make the rest quieter: smaller, lighter, thinner. The screen gets calmer and the ranking gets clearer at the same time." },
        {
          t: "compare",
          a: { label: "Everything loud", lang: "css", src: ".label { font-size: 16px; font-weight: 700; color: #000; }\n.value { font-size: 18px; font-weight: 700; color: #000; }\n.hint  { font-size: 16px; font-weight: 700; color: #000; }" },
          b: { label: "Ranked", lang: "css", src: ".label { font-size: 13px; font-weight: 500; color: #6b6b6b; }\n.value { font-size: 28px; font-weight: 600; color: #111; }\n.hint  { font-size: 13px; font-weight: 400; color: #8a8a8a; }" },
          x: "Same markup. B pulls three levers at once for the value (size, weight, contrast) and pushes the label and hint down. Nothing new was added.",
        },
        { t: "say", h: "The squint test", x: "Blur your eyes, or the screen, until words turn into shapes. Whatever survives the blur is what people see first. If that isn't the thing that matters, the hierarchy is lying." },
        {
          t: "play",
          mode: "html",
          title: "squint.html",
          html: "<div class=\"stage\">\n  <div class=\"card\">\n    <span class=\"badge\">SALE -20%</span>\n    <h2>Harbour View Room</h2>\n    <p class=\"meta\">2 guests, sea view, free cancellation</p>\n    <p class=\"price\">$184 <small>/ night</small></p>\n    <div class=\"row\">\n      <a href=\"#\" class=\"more\">See all 48 photos and reviews</a>\n      <button class=\"book\">Book now</button>\n    </div>\n  </div>\n</div>\n<button id=\"squint\">Toggle squint</button>",
          css: "body { font-family: system-ui, sans-serif; padding: 24px; background: #f4f4f2; }\n.stage { transition: filter .2s; }\n.stage.blur { filter: blur(6px); }\n.card { background: #fff; padding: 24px; border-radius: 12px; max-width: 420px; }\n.badge { background: #e11d48; color: #fff; font-weight: 800; padding: 6px 10px; font-size: 18px; }\nh2 { font-size: 20px; font-weight: 500; color: #555; margin: 16px 0 4px; }\n.meta { font-size: 15px; font-weight: 700; color: #111; margin: 0; }\n.price { font-size: 18px; color: #999; }\n.row { display: flex; justify-content: space-between; align-items: center; }\n.more { color: #2563eb; font-weight: 700; font-size: 16px; }\n.book { background: #e5e5e5; color: #777; border: 0; padding: 8px 12px; font-size: 13px; }\n#squint { margin-top: 16px; }",
          js: "document.getElementById('squint').onclick = () =>\n  document.querySelector('.stage').classList.toggle('blur');",
          task: "Toggle the blur. Change only the CSS until the reading order under blur is: room name, price, Book now. The badge and the link should fade to the back.",
        },
        {
          t: "quiz",
          q: "A screen 'feels flat', so you add a fourth heading size. Squinting still shows mush. What's the likely real problem?",
          options: ["Still not enough sizes", "Too many things share the top rank, so no single size change fixes it", "The font is wrong", "The colours are too dark"],
          answer: 1,
          why: "Hierarchy is relative. If six things are bold and dark, a bigger seventh just joins the fight. Demote most of them first; then one modest bump is enough.",
        },
        {
          t: "pitfall",
          h: "If it dies in grayscale, it wasn't hierarchy",
          x: "Colour alone is the weakest ranking lever: about 1 in 12 men can't split red from green, and glare, dim screens and print flatten hue. Run `filter: grayscale(1)` on the page. If the order survives, it's built on size, weight and space, which is what you want.",
        },
      ],
    },
    {
      title: "Spacing is a system",
      beats: [
        { t: "say", x: "Random spacing is the fastest tell of a developer-built UI: 13px here, 17px there, 22px because it looked fine once. The fix isn't taste. It's a **scale**: a short list of allowed values, and nothing else." },
        {
          t: "code",
          lang: "css",
          file: "tokens.css",
          src: ":root {\n  --space-1: 4px;\n  --space-2: 8px;\n  --space-3: 12px;\n  --space-4: 16px;\n  --space-5: 24px;\n  --space-6: 32px;\n  --space-7: 48px;\n  --space-8: 64px;\n  --space-9: 96px;\n}",
          note: "Steps grow roughly geometrically. At 8px a 4px change is huge; at 88px it's invisible, so the scale skips it.",
        },
        { t: "say", h: "Why multiples of 4 and 8", x: "They land on whole device pixels at 1.5x, 2x and 3x screens, and most icon grids and type sizes are multiples of 4 already. The bigger win is fewer choices: picking from nine values is fast, and every screen ends up agreeing." },
        { t: "say", h: "Internal < external", x: "Space inside a group must be smaller than space between groups. That one inequality is how the eye knows what belongs together. It's Gestalt **proximity**, and it beats borders, boxes and colour." },
        {
          t: "predict",
          lang: "css",
          src: "/* A */\n.field label { display: block; margin-bottom: 16px; }\n.field       { margin-bottom: 16px; }\n\n/* B */\n.field label { display: block; margin-bottom: 6px; }\n.field       { margin-bottom: 24px; }",
          q: "A form with three label and input pairs. Which makes it obvious which label goes with which input?",
          options: ["A: even spacing looks tidier", "B: labels hug their inputs", "Same thing; spacing is cosmetic"],
          answer: 1,
          why: "In A every gap is equal, so a label sits as close to the input above it as to its own. The eye can't group. B makes the inside gap 4x smaller than the outside gap and grouping becomes instant, no boxes needed.",
        },
        {
          t: "play",
          mode: "html",
          title: "fix-the-spacing.html",
          html: "<form>\n  <h2>Profile</h2>\n  <p class=\"sub\">This is shown on your public page.</p>\n  <div class=\"field\"><label>Name</label><input value=\"Ada Lovelace\"></div>\n  <div class=\"field\"><label>Handle</label><input value=\"@ada\"></div>\n  <h2>Notifications</h2>\n  <p class=\"sub\">Where we reach you.</p>\n  <div class=\"field\"><label>Email</label><input value=\"ada@example.com\"></div>\n  <div class=\"field\"><label>Phone</label><input value=\"+44 20 7946 0000\"></div>\n  <button>Save</button>\n</form>",
          css: ":root { --s1: 4px; --s2: 8px; --s3: 12px; --s4: 16px; --s5: 24px; --s6: 32px; --s7: 48px; }\nbody { font-family: system-ui, sans-serif; padding: 20px; color: #1a1a1a; }\nform { max-width: 360px; }\nh2 { font-size: 18px; margin: 19px 0 13px; }\n.sub { color: #666; font-size: 14px; margin: 7px 0 22px; }\n.field { margin-bottom: 11px; }\nlabel { display: block; font-size: 13px; margin-bottom: 14px; }\ninput { width: 100%; box-sizing: border-box; padding: 9px 7px; font: inherit; border: 1px solid #ccc; border-radius: 6px; }\nbutton { margin-top: 5px; padding: 10px 18px; font: inherit; }",
          task: "Replace every raw px margin and padding with a `var(--sN)`. Rule: label-to-input < field-to-field < section-to-section. The first h2 should have no top margin.",
        },
        {
          t: "pitfall",
          h: "Line-height adds invisible spacing",
          x: "A 16px label at `line-height: 1.5` has 4px of empty half-leading above and below, plus the gap between cap tops and the line box. Your 8px gap reads as 16px or more. Judge gaps by glyph edges, or trim with `text-box: trim-both cap alphabetic` where supported.",
        },
        {
          t: "pitfall",
          h: "Nested corners must shrink",
          x: "A rounded card with padding, holding a rounded button with the same radius, looks subtly wrong: the curves aren't concentric. Inner radius = outer radius - padding. A 20px card with 8px padding wants a 12px inner radius.",
        },
        {
          t: "quiz",
          q: "Card padding is 16px. The gap between the card's title and its body text is 28px. What does the eye see?",
          options: ["A well-spaced card", "A title that seems to belong to the card edge, not to its content", "Nothing, gaps inside a card don't matter"],
          answer: 1,
          why: "The title is closer to the border (16px) than to its own text (28px), so proximity attaches it to the frame. Keep internal gaps smaller than the padding around them: say 8px title-to-body inside 16-24px padding.",
        },
      ],
    },
    {
      title: "Alignment and grids",
      beats: [
        { t: "say", x: "Every element draws invisible lines: its start edge, its baseline, its centre. Fewer distinct lines, calmer screen. Count the left edges on a page you admire; it's usually three or four. Messy screens have fifteen." },
        {
          t: "code",
          lang: "css",
          src: ".page {\n  display: grid;\n  grid-template-columns: repeat(12, minmax(0, 1fr));\n  column-gap: 24px;\n  max-width: 1200px;\n  margin-inline: auto;\n  padding-inline: 24px;\n}\n.main  { grid-column: 1 / span 8; }\n.aside { grid-column: 9 / -1; }\n\n@media (max-width: 720px) {\n  .main, .aside { grid-column: 1 / -1; }\n}",
          mark: [3],
          note: "12 splits into halves, thirds, quarters and sixths. `minmax(0, 1fr)` stops one long word or URL from making its column wider than the rest.",
        },
        { t: "viz", name: "grid", props: { template: "repeat(12, minmax(0, 1fr))" } },
        { t: "say", h: "Baseline rhythm, web edition", x: "Print locks every line to a baseline grid. On the web that fights you: fonts carry different metrics and content reflows. You get most of the effect by keeping line-heights and gaps on the 4px scale and trimming text boxes." },
        { t: "say", h: "Optical beats mathematical", x: "The eye judges mass, not bounding boxes. A circle as tall as a square looks smaller. A play triangle centred by its box looks shifted left, because most of its mass sits near the flat side. Nudge until it *looks* right." },
        {
          t: "play",
          mode: "html",
          title: "optical-centre.html",
          html: "<div class=\"row\">\n  <div><div class=\"btn\"><i class=\"tri\"></i></div><p>box-centred</p></div>\n  <div><div class=\"btn\"><i class=\"tri nudged\"></i></div><p>optical</p></div>\n</div>\n<div class=\"row\">\n  <div class=\"shape square\"></div>\n  <div class=\"shape circle\"></div>\n</div>",
          css: "body { font-family: system-ui; padding: 24px; }\n.row { display: flex; gap: 40px; align-items: center; margin-bottom: 32px; }\np { text-align: center; color: #666; font-size: 13px; }\n.btn { width: 96px; height: 96px; border-radius: 50%; background: #111;\n  display: grid; place-items: center; }\n.tri { width: 0; height: 0; border-left: 34px solid #fff;\n  border-top: 20px solid transparent; border-bottom: 20px solid transparent; }\n.nudged { transform: translateX(0px); }\n.shape { width: 64px; height: 64px; background: #111; }\n.circle { border-radius: 50%; }",
          task: "Raise the `translateX` on `.nudged` until it looks centred (usually a few px). Then grow the circle until it looks as big as the square. Note how far past 64px it goes.",
        },
        {
          t: "compare",
          a: { label: "Mathematical", lang: "css", src: ".square, .circle {\n  width: 64px;\n  height: 64px;\n}" },
          b: { label: "Optical", lang: "css", src: ".square { width: 64px; height: 64px; }\n.circle {\n  width: 68px;\n  height: 68px;\n  margin: -2px;\n}" },
          x: "Type designers do the same: round letters like O dip slightly below the baseline and above the x-height so they match flat letters. It's called **overshoot**. Icon sets bake it in; your own shapes need it too.",
        },
        {
          t: "predict",
          lang: "css",
          src: ".btn {\n  display: flex;\n  align-items: center;\n  gap: 8px;\n  font: 500 15px/1.5 system-ui;\n}\n.btn svg { width: 16px; height: 16px; }",
          q: "An icon next to a label, flex-centred. What often looks off?",
          options: ["Nothing: flex centres it exactly", "The text looks a hair low or high beside the icon", "The gap is too small", "The icon blurs"],
          answer: 1,
          why: "Flex centres the line box, not the letters. The box includes ascender and descender space that rarely splits evenly, so the visual centre of the text drifts. Nudge the icon a pixel, or trim the text box to cap height and baseline.",
        },
        {
          t: "quiz",
          q: "Three cards in a row have 1, 2 and 3-line titles, so their bottom buttons sit at different heights. Cleanest fix?",
          options: ["Truncate every title to one line", "Make each card a flex column and give the button `margin-top: auto`", "Give the cards a fixed height", "Put the buttons outside the cards"],
          answer: 1,
          why: "Grid rows already stretch the cards to equal height. Inside, `display: flex; flex-direction: column` plus `margin-top: auto` pins every button to one bottom line, whatever the title length. No magic numbers.",
        },
        {
          t: "pitfall",
          h: "Centred paragraphs make the eye hunt",
          x: "With centred text every line starts somewhere new, so the eye searches for each start. Centre 1-3 short lines: a hero, an empty state, a dialog title. Anything longer, align to the start edge and let the ragged edge be the far one.",
        },
      ],
    },
    {
      title: "Density and the one action",
      beats: [
        { t: "say", x: "Whitespace isn't empty. It tells the eye where one idea ends. But density isn't a sin either: a trading screen or an IDE needs it. The question is never 'how much space' but whether the density is *organised*." },
        {
          t: "table",
          head: ["Screen", "Density", "What keeps it readable"],
          rows: [
            ["Landing page", "Low", "One idea per viewport; space signals calm and confidence"],
            ["Settings, forms", "Medium", "Tight inside groups, generous between them"],
            ["Tables, dashboards, IDEs", "High", "Strict alignment, tabular numbers, muted chrome, colour only for meaning"],
          ],
        },
        { t: "say", h: "One primary action", x: "Each view gets at most one filled, high-contrast button. The rest step down: secondary (outline or tint), tertiary (text only). Two primaries is zero primaries: the user now has to make the decision you skipped." },
        {
          t: "play",
          mode: "html",
          title: "one-primary.html",
          html: "<div class=\"dialog\">\n  <h3>Unsaved changes</h3>\n  <p>You edited 3 fields in \"Quarterly report\".</p>\n  <div class=\"actions\">\n    <button class=\"danger\">Delete report</button>\n    <button>Cancel</button>\n    <button>Save as draft</button>\n    <button>Save</button>\n  </div>\n</div>",
          css: "body { font-family: system-ui, sans-serif; padding: 24px; background: #eceae6; }\n.dialog { background: #fff; padding: 24px; border-radius: 12px; max-width: 460px; }\nh3 { margin: 0 0 8px; }\np { margin: 0 0 24px; color: #555; }\n.actions { display: flex; gap: 8px; }\nbutton { font: 600 14px system-ui; padding: 10px 14px; border-radius: 8px;\n  border: 0; background: #2563eb; color: #fff; }\n.danger { background: #dc2626; }\n\n/* hint: .actions { justify-content: ... } and margin-right: auto */",
          task: "Make Save the only filled button, Save as draft an outline, Cancel text-only. Push Delete to the far left with `margin-right: auto` and make it a quiet red text button.",
        },
        {
          t: "predict",
          lang: "html",
          src: "<!-- bottom of a settings page -->\n<button class=\"primary\">Save changes</button>\n<button class=\"???\">Delete account</button>",
          q: "How should 'Delete account' look?",
          options: ["Filled red, it's the most serious action", "Filled blue like Save, for consistency", "Quiet red text or outline, away from Save, opening a confirm step", "Hidden behind a hover"],
          answer: 2,
          why: "Destructive actions should be findable, not tempting. Keep them quiet and far from the common action so a misclick can't hit them. The loud red button belongs in the confirm dialog, where the user has already chosen.",
        },
        {
          t: "pitfall",
          h: "Borders are the lazy separator",
          x: "When groups feel muddled the reflex is a 1px line. Try, in order: more space between groups, a subtle background tint, then a border. Every line is another edge for the eye to process; screens full of dividers read like spreadsheets.",
        },
        {
          t: "quiz",
          q: "A dense data table is hard to scan. Which change helps most without adding space?",
          options: ["Bright zebra stripes", "Right-align numbers, use tabular figures, left-align text, mute secondary columns", "Centre every cell", "Bold the header row harder"],
          answer: 1,
          why: "Right-aligned tabular digits line up by place value, so the eye compares magnitudes by length. Consistent alignment creates columns; muting secondary data creates rank. Stripes help a little, loud stripes add noise.",
        },
      ],
    },
    {
      title: "Gestalt and reading patterns",
      beats: [
        { t: "say", x: "Gestalt is a long list of perception laws. Five of them do nearly all the work in interfaces. Learn these and skip the rest." },
        {
          t: "table",
          head: ["Principle", "The rule", "In a UI"],
          rows: [
            ["Proximity", "Near things are one group", "Label close to its input; sections split by space"],
            ["Similarity", "Things that look alike act alike", "Every link one style; never style plain text like a link"],
            ["Common region", "A shared background or border makes a group", "Cards, table rows, a toolbar strip"],
            ["Continuity", "The eye follows lines and edges", "Aligned left edges read as one column"],
            ["Figure and ground", "One layer is in front, the rest is backdrop", "Modals dim the page; menus cast a shadow"],
          ],
        },
        {
          t: "predict",
          lang: "html",
          src: "<!-- four chips in a row -->\n<span class=\"blue\">A</span><span class=\"red\">B</span>\n<!-- 32px gap here -->\n<span class=\"blue\">C</span><span class=\"red\">D</span>\n\n<style>\n  span { margin-right: 6px; }\n  .blue { background: #2563eb; }\n  .red  { background: #dc2626; }\n</style>",
          q: "Which groups does the eye see?",
          options: ["By colour: (A C) and (B D)", "By space: (A B) and (C D)", "No groups at all", "One group of four"],
          answer: 1,
          why: "Proximity usually beats similarity: space is a strong grouping signal, colour a weak one. Wrap A and C in a shared background (common region) and that beats both. Use this order when you need to group things on purpose.",
        },
        { t: "say", h: "F and Z", x: "Eye-tracking on text-heavy pages shows an **F**: a full read of the first lines, a shorter second sweep, then a skim down the left edge. Sparse pages get a **Z**: across the top, diagonal, across the bottom. Neither is a law; both say *front-load*." },
        {
          t: "compare",
          a: { label: "Buried", lang: "text", src: "You have some invoices that are overdue (3)\nThere is a new version of the app available\nYour team has invited 2 new members" },
          b: { label: "Front-loaded", lang: "text", src: "3 invoices overdue\nUpdate available: v4.2\n2 new team members" },
          x: "The skim down the left edge only catches the first two or three words of each line. Put the information there. Cut the preamble.",
        },
        {
          t: "quiz",
          q: "A sidebar reads 'Manage users', 'Manage roles', 'Manage billing', 'Manage API keys'. What does the F-pattern suggest?",
          options: ["It's consistent, leave it", "Drop 'Manage': the left-edge skim sees four identical first words", "Bold the second word", "Sort alphabetically"],
          answer: 1,
          why: "The scan down the left edge reads first words. Four identical ones carry zero information and force a second, slower pass. 'Users, Roles, Billing, API keys' is scannable at a glance.",
        },
        {
          t: "pitfall",
          h: "Card grids kill the scan line",
          x: "A grid of equal cards has no single left edge to skim, so people search it more slowly than a list. For things users compare or hunt through (files, orders, settings), an aligned list usually wins. Cards suit browsing visual things, like products or photos.",
        },
      ],
    },
    {
      title: "Balance and tension",
      beats: [
        { t: "say", x: "Visual weight is roughly size times darkness times saturation times density. A small, saturated, isolated badge can outweigh a large pale photo. Balance means the weight doesn't pile into one corner by accident." },
        { t: "say", h: "Symmetry is safe, asymmetry is alive", x: "Centred, symmetric layouts feel formal and still. Asymmetry (a big heading on one side, a small dense block on the other, space as the counterweight) feels deliberate. Tension is imbalance on purpose: it points the eye." },
        {
          t: "compare",
          a: { label: "Symmetric", lang: "css", src: ".hero {\n  display: grid;\n  place-items: center;\n  text-align: center;\n}\n/* heading, text, button: all centred */" },
          b: { label: "Asymmetric", lang: "css", src: ".hero {\n  display: grid;\n  grid-template-columns: 7fr 5fr;\n  align-items: end;\n}\n/* big heading left, stat + button right */" },
          x: "A is fine and forgettable. B puts weight on the left and lets the smaller, denser right column balance it, which gives the eye a path: heading, then stat, then action.",
        },
        {
          t: "play",
          mode: "html",
          title: "balance.html",
          html: "<section class=\"hero\">\n  <h1>Ship the boring parts faster.</h1>\n  <div class=\"side\">\n    <p class=\"stat\">4.2x</p>\n    <p class=\"cap\">median faster deploys after month one</p>\n    <button>Start free</button>\n  </div>\n</section>",
          css: ":root { --a: 7fr; --b: 5fr; --align: end; }\nbody { font-family: system-ui, sans-serif; margin: 0; padding: 32px; }\n.hero { display: grid; grid-template-columns: minmax(0, var(--a)) minmax(0, var(--b));\n  gap: 32px; align-items: var(--align); min-height: 260px; }\nh1 { font-size: clamp(32px, 6vw, 56px); line-height: 1.05; margin: 0;\n  letter-spacing: -0.02em; }\n.stat { font-size: 40px; font-weight: 700; margin: 0; }\n.cap { color: #666; margin: 4px 0 16px; max-width: 24ch; }\nbutton { font: 600 15px system-ui; padding: 12px 18px; border: 0;\n  border-radius: 8px; background: #111; color: #fff; }",
          task: "Try `--a`/`--b` at 6fr/6fr and 8fr/4fr, and `--align` as start, center, end. Pick the combination where the eye travels heading, stat, button without doubling back.",
        },
        {
          t: "quiz",
          q: "A layout feels heavy on the left: a big dark photo there, light text on the right. Cheapest fix?",
          options: ["Add a second photo on the right", "Put one small, dark, dense element on the right (a stat, a bold number, a button)", "Make the page wider", "Centre everything"],
          answer: 1,
          why: "Weight comes from darkness and density, not only area. A compact dark element balances a large light-ish mass. Adding another big photo just doubles the weight and removes the focal point.",
        },
      ],
    },
    {
      title: "Critique and deliberate copying",
      beats: [
        {
          t: "steps",
          h: "The five-minute critique",
          items: [
            "Name the one job of this screen in one sentence. If you can't, fix that first.",
            "Squint. Is the first shape that survives the blur the one doing the job?",
            "Count font sizes, weights, colours, spacing values and left edges. More than ~5 of any is noise.",
            "Check grouping: is internal space smaller than external space everywhere?",
            "Find the primary action. Exactly one? Is it where the eye ends up?",
            "Stress it: longest name, zero items, 1,000 items, error, loading, 320px wide.",
            "Grayscale it. Does the ranking survive without colour?",
            "Fix the single worst thing. Run the list again.",
          ],
        },
        { t: "say", h: "Copy on purpose", x: "Painters learned by copying masters stroke for stroke. Do the same with screens: rebuild a great interface from a screenshot until a 50% overlay matches. You'll find decisions you'd never notice by looking." },
        {
          t: "steps",
          h: "The study method",
          items: [
            "Pick one screen from a shipped product you admire. Real UI with real data, not a concept shot.",
            "Screenshot at 1x. Pin it behind your page at 50% opacity.",
            "Rebuild it in plain HTML and CSS until the edges line up.",
            "Extract its system: every font size, weight, colour, gap and radius. Usually far fewer than you'd guess.",
            "Write down three decisions that surprised you, and why you think they made them.",
            "Change one value and look again. Now you know why they didn't.",
          ],
        },
        {
          t: "rebuild",
          h: "A designer's debug toolbar",
          x: "Build three toggles every designer uses daily: squint (blur), grayscale, and outline every box to reveal alignment edges. The blur one works; finish the other two.",
          mode: "html",
          html: "<div class=\"bar\">\n  <button data-mode=\"blur\">Squint</button>\n  <button data-mode=\"gray\">Grayscale</button>\n  <button data-mode=\"lines\">Edges</button>\n</div>\n<main id=\"page\">\n  <h1>Team settings</h1>\n  <p>Manage who can see and change this workspace.</p>\n  <ul><li>Ada, Owner</li><li>Grace, Admin</li><li>Linus, Member</li></ul>\n  <button class=\"cta\">Invite people</button>\n</main>",
          css: "body { font-family: system-ui; margin: 0; }\n.bar { position: sticky; top: 0; display: flex; gap: 8px; padding: 8px;\n  background: #111; }\n.bar button { font: 600 13px system-ui; }\nmain { padding: 24px; }\n.cta { background: #2563eb; color: #fff; border: 0; padding: 10px 16px;\n  border-radius: 8px; }\n.blur { filter: blur(5px); }\n/* TODO: .gray, and .lines * { outline: ... } */",
          js: "document.querySelectorAll('.bar button').forEach((b) => {\n  b.onclick = () => {\n    const mode = b.dataset.mode;\n    if (mode === 'blur') document.getElementById('page').classList.toggle('blur');\n    // TODO: gray and lines\n  };\n});",
          task: "Add `.gray` (grayscale filter) and `.lines *` (a 1px translucent outline on every element). Then find two misaligned edges in the sample page.",
        },
        {
          t: "quiz",
          q: "Where does the most useful design study material come from?",
          options: ["Award-winning concept shots", "Shipped products used daily, which survived real content and real users", "Free templates", "Your own old work"],
          answer: 1,
          why: "Concept shots are optimised to look good in a thumbnail with perfect data. Shipped products had to survive long names, empty states, 12 locales and angry users; their decisions carry real reasons.",
        },
        {
          t: "pitfall",
          h: "Mockup content is fake content",
          x: "Concept shots use perfect names, round numbers and exactly six items. Real data has 'Maximiliano Fernández-Oyarzábal', zero items, and a 14-digit total. Design with the ugliest real data first; pretty data hides every layout bug you have.",
        },
        {
          t: "mission",
          h: "Critique and fix one real screen",
          x: "Take a screen you built. Run the five-minute critique and write down every finding. Fix the worst three. Screenshot before and after side by side. If you can't name each improvement in one sentence, it wasn't one.",
          hint: "Start with counting: list every distinct font size and spacing value in DevTools (Computed tab). Collapsing them onto a scale fixes half the problems on its own.",
        },
      ],
    },
  ],
  nobodyTells: [
    "Most 'this looks off' feedback is a spacing problem. Check gaps against the scale before touching colour or fonts.",
    "De-emphasising the rest works better than emphasising the important thing. Grey is the most useful colour you own.",
    "Inner radius = outer radius - padding. Matching radii on nested boxes is why so many cards look slightly wrong.",
    "Designers measure from glyph edges, developers from boxes. Line-height padding is why your 8px gap looks like 16.",
    "Before you add a divider line, try adding space. Before you add a colour, try adding weight.",
    "Test every screen with the longest real name and zero items before you show it to anyone.",
    "A screen you can't describe in one sentence can't have a clear hierarchy, because you don't know what ranks first.",
  ],
  glossary: [
    ["visual hierarchy", "The order in which the eye visits elements, set by size, weight, contrast, space and position."],
    ["squint test", "Blurring a screen to see which shapes dominate before any words are read."],
    ["spacing scale", "A fixed, short list of allowed gap values, usually on a 4 or 8px base."],
    ["proximity", "Gestalt rule: things placed close together are seen as one group."],
    ["common region", "Gestalt rule: things inside a shared background or border are seen as one group."],
    ["optical alignment", "Positioning by perceived mass rather than bounding box, like nudging a play icon right."],
    ["overshoot", "Letting round shapes extend slightly past flat ones so they look the same size."],
    ["visual weight", "How strongly an element pulls the eye: size, darkness, saturation, density, isolation."],
  ],
  explain: "Explain to a friend why a label should usually be quieter than the value it describes, and how the squint test proves it.",
};
