export default {
  id: "colour",
  n: 40,
  part: "G",
  title: "Colour",
  hook: "Hex codes aren't light and HSL's lightness is a lie. Build palettes on what the eye actually reads.",
  minutes: 70,
  levels: ["use", "understand"],
  sections: [
    {
      title: "The eye reads lightness",
      beats: [
        { t: "say", x: "The eye splits a colour into lightness, chroma and hue, and weights them unequally. **Lightness** carries edges, text and hierarchy. Hue and chroma are paint on top. Get lightness right and a palette survives grayscale, colour blindness and a bad projector." },
        {
          t: "predict",
          lang: "html",
          src: "<button style=\"background: hsl(60 100% 50%); color: white\">Save</button>\n<button style=\"background: hsl(240 100% 50%); color: white\">Save</button>",
          q: "Both backgrounds say `50%` lightness. Which white label is readable?",
          options: ["Both, same lightness", "Only the yellow one", "Only the blue one", "Neither"],
          answer: 2,
          why: "HSL's 50% isn't what the eye sees. That yellow is nearly white (OKLCH L 0.97): white text on it is 1.07:1, invisible. The blue sits at L 0.45: 8.59:1. Same number, opposite ends of the range.",
        },
        { t: "say", h: "Simultaneous contrast", x: "The eye judges a colour against its neighbours, never alone. A grey on black looks lighter than the same grey on white, and a neutral next to orange leans blue. The swatch you picked on a white artboard isn't the one on your dark sidebar." },
        {
          t: "play",
          mode: "html",
          title: "same-grey.html",
          html: "<div class=\"strip\"><div class=\"bar\"></div></div>\n<div class=\"row\">\n  <div class=\"box\" style=\"background:#111\"><i></i></div>\n  <div class=\"box\" style=\"background:#eee\"><i></i></div>\n  <div class=\"box\" style=\"background:#e8590c\"><i></i></div>\n</div>\n<button id=\"b\">Flatten the strip</button>",
          css: "body { font-family: system-ui, sans-serif; padding: 20px; }\n.strip { position: relative; height: 110px; border-radius: 8px;\n  background: linear-gradient(90deg, #000, #fff); }\n.flat .strip { background: #9a9a9a; }\n.bar { position: absolute; left: 6%; right: 6%; top: 42px; height: 26px;\n  background: #808080; }\n.row { display: flex; gap: 12px; margin: 16px 0; flex-wrap: wrap; }\n.box { width: 120px; height: 100px; display: grid; place-items: center;\n  border-radius: 8px; }\n.box i { width: 40px; height: 40px; background: #808080; }",
          js: "b.onclick = () => document.body.classList.toggle('flat');",
          task: "The bar is one flat #808080, end to end. It looks like a gradient running the wrong way. Flatten the strip to prove it, then compare the three small squares: all the same grey.",
        },
        {
          t: "quiz",
          q: "A saturated orange and a neutral grey are tuned to the exact same OKLCH lightness. Side by side, which looks brighter?",
          options: ["They match: that's what equal lightness means", "The orange", "The grey", "Depends on the screen only"],
          answer: 1,
          why: "Saturated colours look brighter than a grey of equal luminance (the Helmholtz-Kohlrausch effect). OKLCH doesn't model it, so equal-L numbers get you close and your eye does the last step.",
        },
        {
          t: "pitfall",
          h: "Swatches picked in isolation",
          x: "A colour chosen on a white canvas shifts on every surface it lands on, and small areas read darker and duller than big ones: the orange that's perfect as a card is murky as a 6px dot. Judge colours in the real UI, on every background, at real size, in both themes.",
        },
      ],
    },
    {
      title: "Hex codes aren't light",
      beats: [
        { t: "say", x: "The numbers in `#808080` are **sRGB-encoded**: a curve spends more codes on darks, where the eye is sensitive. Decode 128 and you get about 22% of white's light, yet it looks close to middle grey. Storage is perceptual-ish; light is linear." },
        {
          t: "code",
          lang: "js",
          src: "// sRGB code (0-255) -> linear light (0-1)\nconst toLinear = (v) => {\n  v /= 255;\n  return v <= 0.04045 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4;\n};\n\ntoLinear(128); // 0.216: 'half' grey emits ~22% of white's light\ntoLinear(188); // 0.502: this is the real half",
          note: "This is the same decode WCAG's contrast formula starts with. Every blend done on the raw codes is done on a curve, not on light.",
        },
        {
          t: "predict",
          lang: "css",
          src: ".bar {\n  background: linear-gradient(to right, #ff0000, #00ff00);\n}",
          q: "What colour sits in the middle of this bar?",
          options: ["Bright yellow, #ffff00", "Dark olive, #808000", "Neutral grey", "Golden, #d0a800"],
          answer: 1,
          why: "Gradients whose stops are all hex, rgb() or hsl() blend the encoded sRGB numbers, for web compatibility. Halfway is (128, 128, 0): each channel at ~22% light. A dark, muddy dip no mix of real light would make.",
        },
        {
          t: "play",
          mode: "html",
          title: "four-spaces.html",
          html: "<label>from <input type=\"color\" id=\"a\" value=\"#ff0000\"></label>\n<label>to <input type=\"color\" id=\"b\" value=\"#00ff00\"></label>\n<div id=\"out\"></div>",
          css: "body { font: 14px system-ui, sans-serif; padding: 20px; }\nlabel { margin-right: 12px; }\n.row { margin-top: 14px; }\n.row code { display: block; margin-bottom: 4px; color: #555; }\n.g { height: 44px; border-radius: 6px; }",
          js: "const spaces = ['srgb', 'srgb-linear', 'oklab', 'oklch'];\nconst render = () => {\n  out.innerHTML = spaces.map((s) =>\n    `<div class=\"row\"><code>in ${s}</code><div class=\"g\" style=\"background: linear-gradient(to right in ${s}, ${a.value}, ${b.value})\"></div></div>`\n  ).join('');\n};\na.oninput = b.oninput = render;\nrender();",
          task: "Red to green: sRGB dips to olive, OKLab stays bright. Try blue (#0000ff) to yellow (#ffff00): sRGB goes grey. Then blue to white: which row drifts purple?",
        },
        {
          t: "table",
          head: ["Space", "Red to green, halfway", "Use it for"],
          rows: [
            ["`srgb` (encoded)", "#808000, dark olive", "Nothing new: it's only the legacy default for hex-only gradients"],
            ["`srgb-linear`", "#bcbc00, bright", "Physics: blending light, blur, image resizing, 3D lighting"],
            ["`oklab`", "#d0a800, golden", "UI gradients and mixes: equal steps look equal"],
            ["`oklch`", "Arcs round the hue wheel", "Hue sweeps; can leave gamut and get mapped"],
          ],
          caption: "Encoded sRGB is a storage format. It's the worst place to do maths on colour.",
        },
        {
          t: "pitfall",
          h: "Hex stops lock a gradient into sRGB",
          x: "CSS defaults to OKLab for interpolation, except between legacy colours: a gradient of only hex, rgb() or hsl() blends in encoded sRGB to keep old pages identical. Write `in oklab` in the gradient, or make one stop `oklch()`, and the muddy middle goes away.",
        },
        {
          t: "quiz",
          q: "Which of these should be computed in linear light rather than OKLab?",
          options: ["A 10-step grey ramp", "A hover shade for a button", "Two glows overlapping additively in a shader", "A sequential chart scale"],
          answer: 2,
          why: "Adding light is physics, and physics happens in linear light; do it on encoded values and overlaps come out too dark. Everything a person judges as 'evenly spaced' belongs in a perceptual space like OKLab.",
        },
      ],
    },
    {
      title: "HSL lies, OKLCH doesn't",
      beats: [
        { t: "say", x: "HSL is the RGB cube bent into a cylinder. Its L is the average of the largest and smallest channel, not anything the eye measures. That's why every hue at `l: 50%` lands at a different real lightness, from near-white yellow to deep blue." },
        {
          t: "play",
          mode: "html",
          title: "hsl-vs-oklch.html",
          html: "<p>hsl(h 100% 50%), and the lightness the eye reads</p>\n<div class=\"row\" id=\"hsl\"></div><div class=\"row\" id=\"hslL\"></div>\n<p>oklch(70% 0.11 h), and its lightness</p>\n<div class=\"row\" id=\"ok\"></div><div class=\"row\" id=\"okL\"></div>",
          css: "body { font: 14px system-ui, sans-serif; padding: 20px; }\np { margin: 18px 0 6px; color: #444; }\n.row { display: flex; }\n.row div { flex: 1; height: 44px; }",
          js: "const hues = Array.from({ length: 12 }, (_, i) => i * 30);\nconst fill = (id, f) => {\n  document.getElementById(id).innerHTML =\n    hues.map((h) => `<div style=\"background: ${f(h)}\"></div>`).join('');\n};\nconst hsl = (h) => `hsl(${h} 100% 50%)`;\nconst ok = (h) => `oklch(70% 0.11 ${h})`;\nfill('hsl', hsl);\nfill('ok', ok);\n// relative colour: keep the colour's OKLCH lightness, drop chroma\nfill('hslL', (h) => `oklch(from ${hsl(h)} l 0 0)`);\nfill('okL', (h) => `oklch(from ${ok(h)} l 0 0)`);",
          task: "The grey rows strip each colour to its OKLCH lightness. HSL's grey row is a mess; OKLCH's is flat. Push the 0.11 to 0.2: the flat row holds, but some hues now leave sRGB.",
        },
        { t: "say", h: "OKLCH in one line", x: "`oklch(L C H)`: L is perceived lightness from 0 to 1 (or 0-100%), C is chroma from 0 to about 0.4, H is the hue angle. Turn H and lightness stays put. It's the polar form of **OKLab**, Björn Ottosson's 2020 perceptual space." },
        {
          t: "compare",
          a: { label: "HSL: same numbers, uneven", lang: "css", src: "--chart-1: hsl(0 70% 50%);\n--chart-2: hsl(60 70% 50%);\n--chart-3: hsl(120 70% 50%);\n--chart-4: hsl(240 70% 50%);" },
          b: { label: "OKLCH: same numbers, even", lang: "css", src: "--chart-1: oklch(65% 0.12 25);\n--chart-2: oklch(65% 0.12 90);\n--chart-3: oklch(65% 0.12 150);\n--chart-4: oklch(65% 0.12 260);" },
          x: "In A the yellow and green glow and the blue sinks, so one series looks more important for no reason. In B every series has the same weight; only hue changes.",
        },
        {
          t: "predict",
          lang: "css",
          src: ":root {\n  --danger:  oklch(55% 0.19 25);  /* #c92f33 */\n  --success: oklch(55% 0.13 150); /* #298646 */\n  --info:    oklch(55% 0.13 250); /* #2a75ba */\n}\n/* white text on each */",
          q: "Same OKLCH lightness. Do all three give the same WCAG contrast with white text?",
          options: ["Yes: equal L means equal contrast", "No: roughly 5.3, 4.6 and 4.8 to 1", "No: only the red passes", "WCAG can't measure OKLCH"],
          answer: 1,
          why: "WCAG 2 uses relative luminance; OKLab L models perception, and chroma pulls them apart. All three pass here, but a step lighter the green would fail first. Design in OKLCH, then check every pair with the real formula.",
        },
        {
          t: "pitfall",
          h: "HSL steps aren't perceptual steps",
          x: "`hsl(h s calc(l + 20%))` as a hover barely moves pure yellow (OKLCH L 0.97 to 0.97) and moves pure blue a long way (0.45 to 0.60). One rule, a different visible change per hue. Step OKLCH L instead: every hue moves the same perceived distance.",
        },
      ],
    },
    {
      title: "Gamut: past the edge of sRGB",
      beats: [
        { t: "say", x: "Hex codes live in **sRGB**, a 1990s standard. Display P3, on most recent phones and Macs, reaches visibly further into saturated reds, oranges and greens. `oklch()` and `color(display-p3 ...)` can name those colours; hex can't." },
        {
          t: "table",
          head: ["Hue (OKLCH h)", "Max C at L 0.3", "at L 0.5", "at L 0.9"],
          rows: [
            ["Red, 25", "0.12", "0.20", "0.05"],
            ["Yellow, 100", "0.06", "0.10", "0.19"],
            ["Green, 145", "0.10", "0.16", "0.20"],
            ["Blue, 260", "0.12", "0.20", "0.05"],
          ],
          caption: "The most chroma sRGB can show at each lightness. Yellow only exists light; blue only exists dark. The gamut is lumpy.",
        },
        {
          t: "predict",
          lang: "css",
          src: ".badge {\n  /* sRGB tops out near C 0.2 at this L and hue */\n  background: oklch(65% 0.28 145);\n}\n/* viewed on an sRGB office monitor */",
          q: "What does that user see?",
          options: ["The exact colour, the monitor stretches", "Nothing: the declaration is invalid", "The nearest colour the screen can show, picked by the browser's gamut mapping", "Transparent"],
          answer: 2,
          why: "Out-of-gamut values are valid; the browser maps them in. The spec wants chroma reduced in OKLCH, keeping L and H. Engines have not all shipped that, and per-channel clipping can shift hue and lightness. Don't leave it to chance.",
        },
        {
          t: "code",
          lang: "css",
          src: ":root {\n  --accent: oklch(62% 0.19 145);   /* in sRGB: everyone gets this */\n}\n@media (color-gamut: p3) {\n  :root {\n    --accent: oklch(62% 0.25 145); /* more vivid where the screen allows */\n  }\n}",
          note: "Design and contrast-check the sRGB value first. P3 is an enhancement for screens that have it, never the only value.",
        },
        { t: "say", h: "Map by hand: drop chroma", x: "When a ramp step leaves the gamut, lower C and keep L and H. Lightness carries the contrast and the hierarchy; hue is the identity. Saturation is the one thing you can quietly give up." },
        {
          t: "pitfall",
          h: "Designed on a P3 laptop, shipped to sRGB",
          x: "Picked on a P3 MacBook, that green looks electric. Most office monitors are sRGB, where it's mapped down and flatter, and the contrast you checked was for a colour they never see. Check palettes on an sRGB screen, or with DevTools' sRGB gamut line in the colour picker.",
        },
      ],
    },
    {
      title: "Building a palette",
      beats: [
        { t: "say", x: "Most of a UI is neutral: text, borders, surfaces, dividers. A working palette is one neutral ramp of 10-12 steps, one accent ramp, and four semantic colours. Anything more is usually a decision you haven't made yet." },
        {
          t: "code",
          lang: "css",
          file: "palette.css",
          src: ":root {\n  /* neutrals, tinted 260 (cool) at tiny chroma */\n  --n-50:  oklch(98.5% 0.005 260);\n  --n-100: oklch(96% 0.01 260);\n  --n-200: oklch(92% 0.01 260);\n  --n-300: oklch(86% 0.01 260);\n  --n-400: oklch(76% 0.01 260);\n  --n-500: oklch(64% 0.01 260);\n  --n-600: oklch(54% 0.01 260); /* first step with 4.5:1 on white */\n  --n-700: oklch(45% 0.01 260);\n  --n-800: oklch(36% 0.01 260);\n  --n-900: oklch(27% 0.01 260);\n  --n-950: oklch(20% 0.01 260);\n}",
          mark: [3, 9],
          note: "Pure greys look dead next to a coloured accent. A chroma of 0.005-0.015 toward the accent's hue (or its complement, for warmth) ties the whole UI together without anyone noticing why.",
        },
        {
          t: "play",
          mode: "html",
          title: "ramp.html",
          html: "<label>hue <input id=\"h\" type=\"range\" min=\"0\" max=\"359\" value=\"260\"> <b id=\"hv\"></b></label>\n<label>peak chroma <input id=\"c\" type=\"range\" min=\"0\" max=\"0.3\" step=\"0.005\" value=\"0.2\"> <b id=\"cv\"></b></label>\n<div id=\"ramp\"></div>",
          css: "body { font: 13px system-ui, sans-serif; padding: 16px; }\nlabel { display: block; margin-bottom: 6px; }\n#ramp { display: flex; margin-top: 12px; }\n#ramp div { flex: 1; height: 120px; padding: 6px 4px; font-size: 11px;\n  display: flex; flex-direction: column; justify-content: space-between; }\n.cut { text-decoration: underline wavy; }",
          js: "const Ls = [0.97, 0.93, 0.87, 0.79, 0.7, 0.62, 0.55, 0.47, 0.39, 0.31, 0.24];\nconst srgb = (L, C, H) => {\n  const a = C * Math.cos(H * Math.PI / 180), b = C * Math.sin(H * Math.PI / 180);\n  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3;\n  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3;\n  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;\n  return [4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,\n    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,\n    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s];\n};\nconst inGamut = (rgb) => rgb.every((v) => v >= -1e-4 && v <= 1 + 1e-4);\nconst lum = ([r, g, b]) => 0.2126 * r + 0.7152 * g + 0.0722 * b;\nconst render = () => {\n  const H = +h.value, peak = +c.value;\n  hv.textContent = H; cv.textContent = peak;\n  ramp.innerHTML = Ls.map((L, i) => {\n    let C = peak * Math.sin(Math.PI * (i + 1) / (Ls.length + 1)); // less chroma at the ends\n    let cut = false;\n    while (C > 0 && !inGamut(srgb(L, C, H))) { C -= 0.002; cut = true; } // gamut map: drop C only\n    C = Math.max(C, 0);\n    const Y = lum(srgb(L, C, H).map((v) => Math.min(1, Math.max(0, v))));\n    const onWhite = 1.05 / (Y + 0.05);\n    const ink = onWhite >= 4.5 ? '#fff' : '#000';\n    return `<div style=\"background: oklch(${L} ${C.toFixed(3)} ${H}); color: ${ink}\">\n      <span>${Math.round(L * 100)}</span><span class=\"${cut ? 'cut' : ''}\">C ${C.toFixed(2)}</span>\n      <span>${onWhite.toFixed(1)}</span></div>`;\n  }).join('');\n};\nh.oninput = c.oninput = render;\nrender();",
          task: "Each swatch shows L, the chroma actually used (wavy = cut to fit sRGB) and its contrast with white. Sweep the hue: yellow loses chroma at the dark end, blue at the light end.",
        },
        { t: "say", h: "Semantic colours at matched lightness", x: "Danger, warning, success and info should be the same lightness and close in chroma, so none shouts louder than its meaning. Pick one L that passes on your background, then vary only hue. Their tints for backgrounds share one high L too." },
        {
          t: "code",
          lang: "css",
          src: ":root {\n  --danger:  oklch(55% 0.19 25);  /* 5.3:1 on white */\n  --warning: oklch(55% 0.11 65);  /* 5.0:1 */\n  --success: oklch(55% 0.13 150); /* 4.6:1 */\n  --info:    oklch(55% 0.13 250); /* 4.8:1 */\n\n  --danger-bg:  oklch(96% 0.015 25);\n  --warning-bg: oklch(96% 0.05 95);\n}",
          note: "Ratios computed from the sRGB result of each value. The warning here is amber-brown on purpose: see the next beat.",
        },
        {
          t: "quiz",
          q: "Your warning banner needs to read as 'yellow' and its text must pass 4.5:1 on white. What works?",
          options: ["Yellow text, `#ffcc00`", "A darker yellow, same hue, at L 0.5", "Pale yellow background, dark amber text, a warning icon", "Yellow text with a black outline"],
          answer: 2,
          why: "Yellow only exists at high lightness. At L 0.5 the same hue is olive-brown, not yellow. So yellow-ness has to come from the surface, with dark amber text and an icon carrying the message.",
        },
        {
          t: "pitfall",
          h: "Tints mixed in sRGB drift",
          x: "Tints made by mixing toward white in sRGB wander in hue: pure blue turns lavender on the way, as the gradient play showed. Build ramps by stepping OKLCH L at a fixed hue instead, with slightly tighter gaps at the light end where surfaces live, and less chroma at both ends.",
        },
      ],
    },
    {
      title: "Contrast you can measure",
      beats: [
        { t: "say", x: "WCAG 2 contrast is `(L1 + 0.05) / (L2 + 0.05)` on relative luminance, from 1:1 to 21:1. Level AA asks 4.5:1 for body text, 3:1 for large text (24px, or 18.66px bold) and 3:1 for the parts of controls you need to see, like input borders and focus rings." },
        { t: "viz", name: "contrast", props: { fg: "#777777", bg: "#ffffff" } },
        { t: "say", x: "`#777777` on white is 4.48:1 and fails. `#767676` is 4.54:1 and passes: the lightest pure grey that does. Type `#767676` into the text field above and watch it cross the line." },
        {
          t: "predict",
          lang: "css",
          src: "/* A */ .a { color: #777777; background: #000000; }\n/* B */ .b { color: #ffffff; background: #777777; }",
          q: "Which one passes WCAG 2 AA for body text?",
          options: ["Both", "Only A", "Only B", "Neither"],
          answer: 1,
          why: "A is 4.69:1, B is 4.48:1. Yet B is clearly the easier read: WCAG 2 overrates dark pairs. APCA agrees with your eyes: A scores about Lc 31, B about Lc 77.",
        },
        { t: "say", h: "APCA", x: "**APCA** is a newer contrast model. It knows polarity (dark on light differs from light on dark) and sets the minimum by font size and weight. Its score, Lc, runs to about 106 (negative for light text); 75 is a common floor for body text, 90 is comfortable." },
        { t: "say", h: "Which one is the law", x: "WCAG 3 is still a Working Draft (September 2026) that says its contrast method is yet to be decided; APCA isn't in it. Laws and contracts cite WCAG 2.x AA. So: pass WCAG 2, then use APCA as the second opinion, especially in dark mode." },
        {
          t: "quiz",
          q: "Your brand blue is `#1e88e5`. White labels score 3.68:1, black labels 5.71:1. What do you ship?",
          options: ["Black text: it passes", "White text: it looks better, ignore WCAG", "Darken the blue for buttons until white passes, keep #1e88e5 for large accents", "`contrast-color()`"],
          answer: 2,
          why: "Black passes on paper, but most people read white better on that blue (APCA: Lc 69 vs 40). Shipping a fail is a legal risk. A darker button blue satisfies both models; the bright one can stay on big, non-text shapes.",
        },
        {
          t: "pitfall",
          h: "`contrast-color()` picks black on mid blues",
          x: "Baseline since 2026, it returns black or white by WCAG 2 maths. On `#2277d3`, black wins 4.65 to 4.52, and small black text on that blue is hard work. Use it on clearly light or dark backgrounds, not mid-tones.",
        },
        {
          t: "pitfall",
          h: "Thin weights eat your contrast",
          x: "The ratio is computed on solid colour. A 300-weight 14px grey is mostly antialiased edge pixels, so it renders lighter than its hex. A grey that passes at 4.6:1 in regular weight reads far fainter in light weight. Thin text needs darker values than the checker demands.",
        },
      ],
    },
    {
      title: "Dark mode done right",
      beats: [
        { t: "say", x: "Dark mode isn't `filter: invert(1)`. Inverting flips photos into negatives, turns shadows into glows and your blue accent orange. It's a second palette, designed with the same lightness logic run backwards." },
        {
          t: "table",
          head: ["Thing", "Light theme", "Dark theme"],
          rows: [
            ["Page background", "Near white", "Not #000: around L 0.15-0.2, tinted"],
            ["Body text", "Near black", "Not #fff: around L 0.9-0.93"],
            ["Elevation", "Shadows", "Lighter surface = closer. Shadows barely show"],
            ["Accent", "L ~0.55, full chroma", "Lighter (L ~0.75) and less chroma"],
            ["Borders", "Darker than surface", "Lighter than surface, low contrast"],
          ],
        },
        {
          t: "play",
          mode: "html",
          title: "dark.html",
          html: "<label><input type=\"checkbox\" id=\"pure\"> pure black and white</label>\n<label><input type=\"checkbox\" id=\"loud\"> reuse the light-theme accent</label>\n<div class=\"app\">\n  <div class=\"card\">\n    <h3>Deploy finished</h3>\n    <p>Build 482 is live in three regions. <a href=\"#\">See what changed</a></p>\n    <button>View logs</button>\n    <div class=\"menu\">Menu: one level up</div>\n  </div>\n</div>",
          css: ":root { --bg: oklch(18% 0.01 260); --card: oklch(23% 0.01 260);\n  --menu: oklch(29% 0.012 260); --text: oklch(92% 0.01 260);\n  --muted: oklch(72% 0.01 260); --accent: oklch(78% 0.1 260); --on: oklch(20% 0.02 260); }\n.pure { --bg: #000; --card: #000; --menu: #000; --text: #fff; --muted: #fff; }\n.loud { --accent: oklch(55% 0.2 260); --on: #fff; }\nbody { font: 15px/1.5 system-ui, sans-serif; margin: 0; padding: 16px;\n  background: var(--bg); color: var(--text); }\nlabel { display: block; font-size: 13px; color: var(--muted); }\n.app { padding: 20px 0; }\n.card { background: var(--card); padding: 20px; border-radius: 12px; max-width: 380px; }\nh3 { margin: 0 0 6px; } p { margin: 0 0 16px; color: var(--muted); }\na { color: var(--accent); }\nbutton { font: 600 14px system-ui; padding: 9px 14px; border: 0; border-radius: 8px;\n  background: var(--accent); color: var(--on); }\n.menu { margin-top: 16px; padding: 12px; border-radius: 8px; background: var(--menu);\n  box-shadow: 0 8px 24px #0008; }",
          js: "pure.onchange = () => document.body.classList.toggle('pure', pure.checked);\nloud.onchange = () => document.body.classList.toggle('loud', loud.checked);",
          task: "Tick 'pure black and white': the card and menu vanish (the shadow is invisible on black) and the text starts to glare. Untick it, tick the light accent: the link drops to about 3.4:1 against the card.",
        },
        {
          t: "predict",
          lang: "css",
          src: "/* dark theme. A menu opens over a card. */\n.card { background: oklch(23% 0.01 260); }\n.menu { background: ???; box-shadow: 0 8px 24px #0008; }",
          q: "What makes the menu read as 'in front'?",
          options: ["A bigger shadow", "A darker background than the card", "A lighter background than the card", "The same background, plus a border"],
          answer: 2,
          why: "A dark shadow on a dark surface barely shows. In dark UIs the eye reads closer as lighter, like a surface nearer a light source. Each elevation step gets a few points of L: page, card, menu, dialog.",
        },
        {
          t: "pitfall",
          h: "Pure white on pure black halates",
          x: "Bright text on true black seems to bleed and smear, worst for the many people with astigmatism, and it's tiring in long reads. Use off-white text around L 0.9 on a dark grey around L 0.18. Contrast stays above 12:1; the glare goes.",
        },
        {
          t: "code",
          lang: "css",
          src: ":root {\n  color-scheme: light dark;\n  --bg:     light-dark(oklch(99% 0.005 260), oklch(18% 0.01 260));\n  --text:   light-dark(oklch(25% 0.01 260),  oklch(92% 0.01 260));\n  --accent: light-dark(oklch(55% 0.2 260),   oklch(78% 0.1 260));\n}",
          note: "`light-dark()` (Baseline 2024) follows `color-scheme`, not the media query; that trap is in CSS III: responsive, tokens and motion. Wiring themes to tokens is in Design systems and tokens.",
        },
        {
          t: "quiz",
          q: "You reuse the light theme's `#2f6fed` link colour on a `#121212` page. What happens?",
          options: ["It passes and looks the same", "4.12:1: fails AA, and the saturated blue vibrates on dark", "It becomes invisible", "Browsers adjust it automatically"],
          answer: 1,
          why: "Dark blues lose contrast against dark grounds. A lighter, calmer step of the same hue, like `#8fb1f7`, gives 8.74:1 and stops buzzing. Accents swap to a different step of their ramp per theme.",
        },
      ],
    },
    {
      title: "Colour in CSS today",
      beats: [
        {
          t: "table",
          head: ["Feature", "What it gives you", "Status"],
          rows: [
            ["`oklch()`, `oklab()`", "Perceptual colours, and P3 values in plain CSS", "Baseline 2023"],
            ["`color-mix()`", "Blend two colours in a space you name", "Baseline 2023"],
            ["Relative colour", "`oklch(from var(--x) l c h)`: edit one channel", "Baseline 2024"],
            ["`light-dark()`", "A colour per scheme, following `color-scheme`", "Baseline 2024"],
            ["`contrast-color()`", "Black or white, whichever contrasts more", "Baseline 2026"],
            ["`linear-gradient(in oklab, ...)`", "Pick the interpolation space", "All current engines"],
          ],
        },
        {
          t: "code",
          lang: "css",
          src: ".btn {\n  --accent: oklch(55% 0.2 260);\n  background: var(--accent);\n}\n.btn:hover {\n  background: oklch(from var(--accent) calc(l - 0.06) c h);\n}\n.btn.subtle {\n  background: oklch(from var(--accent) 0.95 calc(c * 0.25) h);\n  color: var(--accent);\n}\n.btn:disabled {\n  background: oklch(from var(--accent) l 0.02 h);\n}",
          note: "One token, every state derived by changing a single channel. Hover darkens by a fixed perceived amount on every hue.",
        },
        {
          t: "predict",
          lang: "css",
          src: ".btn:hover {\n  background: oklch(from var(--accent) calc(l + 10%) c h);\n}",
          q: "What does the hover background become?",
          options: ["10% lighter", "10% of the way to white", "Invalid at computed time, so `unset`: no background", "Clamped at 100%"],
          answer: 2,
          why: "In relative colour, channel keywords resolve to plain numbers: `l` is 0-1, never a percentage. `calc(number + 10%)` is a type error. Because it contains `var()`, it fails late and silently. Write `calc(l + 0.1)`.",
        },
        {
          t: "pitfall",
          h: "Alpha text changes with what's behind it",
          x: "`color: rgb(0 0 0 / 0.55)` for muted text is a different colour on every surface: greyer on white, muddy on a tinted card, near invisible on a dark image. No checker can sign it off. Make muted text a solid token per surface; keep alpha for overlays.",
        },
        {
          t: "say",
          x: "`color-mix(in oklab, var(--accent) 15%, white)` is a solid tint that follows the token. Mix with `transparent` instead and you get the accent at 15% alpha, which shifts on every surface. Percentages that sum under 100% also leak into alpha.",
        },
      ],
    },
    {
      title: "Colour for data, and restraint",
      beats: [
        {
          t: "table",
          head: ["Data", "Scale", "Build it as"],
          rows: [
            ["Ordered: low to high", "Sequential", "One hue (or a gentle sweep), L falling steadily"],
            ["Above or below a midpoint", "Diverging", "Two hues at equal L, meeting at a light neutral"],
            ["Unordered categories", "Categorical", "Distinct hues at similar L; 6-8 at most"],
            ["One thing that matters", "Highlight", "Everything grey, the one series in the accent"],
          ],
        },
        {
          t: "predict",
          lang: "js",
          src: "// heatmap of response times, 0 ms to 2000 ms\nconst colour = (t) => `hsl(${240 - t * 240} 100% 50%)`; // blue -> red rainbow",
          q: "What goes wrong with a rainbow scale?",
          options: ["Nothing, it's the classic choice", "Its lightness rises and falls, so it invents bands: the cyan and yellow zones look like features", "It's too slow to render", "Only that it's ugly"],
          answer: 1,
          why: "The eye reads order from lightness. A rainbow goes dark blue, bright cyan, bright yellow, mid red, so mid values pop and borders appear where the data is smooth. Use a ramp whose L moves one way, like viridis.",
        },
        {
          t: "play",
          mode: "html",
          title: "chart-colours.html",
          html: "<button id=\"g\">grayscale</button>\n<p>red / green status</p><div class=\"bars\" id=\"a\"></div>\n<p>Okabe-Ito, a colour-blind-safe set</p><div class=\"bars\" id=\"b\"></div>",
          css: "body { font: 13px system-ui, sans-serif; padding: 16px; }\n.gray .bars { filter: grayscale(1); }\np { margin: 14px 0 4px; color: #555; }\n.bars { display: flex; align-items: flex-end; gap: 6px; height: 90px; }\n.bars div { width: 34px; border-radius: 4px 4px 0 0; }",
          js: "const hs = [70, 45, 85, 30, 60, 50];\nconst bars = (id, cols) => {\n  document.getElementById(id).innerHTML = hs.map((v, i) =>\n    `<div style=\"height:${v}px; background:${cols[i % cols.length]}\"></div>`).join('');\n};\nbars('a', ['#2e9e44', '#fa6052']);\nbars('b', ['#E69F00', '#56B4E9', '#009E73', '#F0E442', '#0072B2', '#D55E00']);\ng.onclick = () => document.body.classList.toggle('gray');",
          task: "Grayscale: red and green become one grey, so lightness can't split them; for red-green colour blindness, hue can't either. DevTools, Rendering, 'Emulate vision deficiencies': compare both sets.",
        },
        {
          t: "pitfall",
          h: "Red and green as the only signal",
          x: "Red-green deficiencies are the common ones, and a pass/fail column in red and green at similar lightness reads as one colour to them. Pair colour with a second cue (an icon, a label, position) and push the pair apart in lightness. Blue and orange is a safer default pair.",
        },
        { t: "say", h: "Restraint", x: "Colour is the loudest lever and the first to wear out. Neutrals for structure, one accent for the action, semantic colours only for state, data colours only in charts. If removing a colour loses no information, remove it." },
        {
          t: "quiz",
          q: "A dashboard shows 9 metrics, each card in its own bright colour 'so they're easy to tell apart'. Best fix?",
          options: ["Pick 9 more distinct hues", "Neutral cards; titles and position do the identifying; colour only for a metric that's in trouble", "Make each colour a gradient", "Add a legend"],
          answer: 1,
          why: "Nine colours carry no meaning, so the one red card that matters drowns. Identity comes from labels and layout. Colour then becomes a signal: when something turns amber, everyone sees it.",
        },
        {
          t: "mission",
          h: "Rebuild one product's palette in OKLCH",
          x: "Take a site you built. Pull every colour it uses, convert each to OKLCH, and collapse them onto a tinted neutral ramp, one accent ramp and four semantic colours at matched L. Add a designed dark theme. Every text pair must pass 4.5:1 in both themes.",
          hint: "Count before you start: DevTools' CSS Overview panel lists every colour on a page. Expect 30 or more. Aim for under 20 tokens, and derive hovers with relative colour, not new hexes.",
          solution: {
            lang: "js",
            src: "// check every allowed text pair, in both themes, in CI\nconst lin = (v) => (v <= 0.04045 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4);\nconst lum = (hex) => {\n  const [r, g, b] = [1, 3, 5].map((i) => lin(parseInt(hex.slice(i, i + 2), 16) / 255));\n  return 0.2126 * r + 0.7152 * g + 0.0722 * b;\n};\nconst ratio = (a, b) => {\n  const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p);\n  return (x + 0.05) / (y + 0.05);\n};\n\nconst pairs = {\n  light: [['#24272b', '#f6faff'], ['#6b6f75', '#f6faff']],\n  dark:  [['#e4e8ef', '#0f1216'], ['#adb1b8', '#0f1216']],\n};\nfor (const [theme, list] of Object.entries(pairs))\n  for (const [fg, bg] of list) {\n    const r = ratio(fg, bg);\n    if (r < 4.5) throw new Error(`${theme}: ${fg} on ${bg} is ${r.toFixed(2)}:1`);\n  }",
          },
        },
      ],
    },
  ],
  nobodyTells: [
    "Decide lightness first. A palette that works in grayscale works in colour; the reverse is rarely true.",
    "Gradients between hex colours blend in encoded sRGB and go muddy in the middle. Add `in oklab` and the mud is gone.",
    "HSL lightness is arithmetic, not perception. Yellow and blue at `l: 50%` sit at opposite ends of what the eye sees.",
    "Equal OKLCH lightness is not equal WCAG contrast. Design in OKLCH, sign off with the contrast formula.",
    "Yellow can't be dark. Warnings get a pale yellow surface and dark amber text, never yellow text.",
    "In dark mode, elevation is lightness. Shadows vanish on dark grounds; lighter surfaces read as closer.",
    "WCAG 2 overrates dark-on-dark pairs. Pass it for the law, check dark mode with APCA for your readers.",
    "Muted text made with alpha changes colour on every surface. Make it a solid token.",
  ],
  glossary: [
    ["lightness", "How light a colour looks to the eye. The channel that carries text, edges and hierarchy."],
    ["chroma", "Colourfulness: distance from the grey of the same lightness. C in OKLCH."],
    ["sRGB encoding", "The transfer curve applied to RGB values so 8 bits spend more codes on darks; not linear light."],
    ["linear light", "RGB values proportional to emitted light. Where physical blending, blur and lighting belong."],
    ["OKLab / OKLCH", "A perceptual colour space (2020) and its polar form: lightness, chroma, hue with even steps."],
    ["gamut", "The range of colours a space or screen can show. sRGB is smaller than Display P3."],
    ["gamut mapping", "Bringing an out-of-gamut colour inside; done well, it lowers chroma and keeps lightness and hue."],
    ["simultaneous contrast", "A colour's appearance shifting with the colours around it."],
    ["relative luminance", "WCAG 2's weighted sum of linear R, G, B; the input to the contrast ratio."],
    ["APCA", "A contrast model aware of polarity, size and weight, scored as Lc. Not part of any WCAG standard yet."],
    ["halation", "The glow or smear bright text seems to have on a very dark background."],
    ["sequential / diverging / categorical", "The three kinds of data colour scale: ordered, around a midpoint, unordered."],
  ],
  explain: "Explain to a friend why `hsl(60 100% 50%)` and `hsl(240 100% 50%)` look nothing alike in lightness, and how OKLCH fixes it when building a palette.",
};
