export default {
  id: "testing",
  n: 44,
  part: "G",
  title: "Testing and honesty",
  hook: "A test is a bet against your future self. Learn which bets pay, then learn to report results you'd defend.",
  minutes: 75,
  levels: ["use", "understand", "rebuild"],
  sections: [
    {
      title: "What a test buys",
      beats: [
        { t: "say", x: "A test costs minutes of upkeep every time the code around it changes, forever. It pays out once: the day it goes red before a user finds the bug. Rate tests by **confidence per minute of upkeep**, never by count." },
        {
          t: "predict",
          lang: "js",
          src: "function total(items) {\n  let sum = 0;\n  for (const it of items) sum += it.price;   // bug: ignores it.qty\n  return sum;\n}\n\ntest(\"total adds up the cart\", () => {\n  expect(total([{ price: 5, qty: 1 }])).toBe(5);\n});",
          q: "Does this test catch the bug?",
          options: ["Yes, it calls total and checks the result", "No: with qty 1, price and price * qty are equal", "Only if coverage is 100%", "Only with a mock for items"],
          answer: 1,
          why: "The test runs every line, so coverage reports 100%, and the bug walks past. An input where the bug changes the output (qty 3) is what makes a test. Pick inputs that tell the right code from the likely wrong code.",
        },
        {
          t: "play",
          mode: "js",
          title: "mutation testing by hand",
          js: "// The real function, plus hand-made mutants: each is one small bug.\nconst versions = {\n  original:        (x, lo, hi) => Math.min(Math.max(x, lo), hi),\n  \"swap min/max\":  (x, lo, hi) => Math.max(Math.min(x, lo), hi),\n  \"forgot hi\":     (x, lo, hi) => Math.max(x, lo),\n  \"forgot lo\":     (x, lo, hi) => Math.min(x, hi),\n  \"off by one\":    (x, lo, hi) => Math.min(Math.max(x, lo), hi - 1),\n  \"returns x\":     (x, lo, hi) => x,\n};\n\n// The test suite. It runs every line of clamp, so coverage says 100%.\nconst tests = [\n  (clamp) => clamp(5, 0, 10) === 5,\n  (clamp) => clamp(-3, 0, 10) === 0,\n];\n\nlet killed = 0;\nfor (const [name, fn] of Object.entries(versions)) {\n  const passed = tests.every((t) => t(fn));\n  if (name === \"original\") { console.log(\"original passes:\", passed); continue; }\n  if (!passed) killed++;\n  console.log(passed ? \"SURVIVED\" : \"killed  \", name);\n}\nconsole.log(`mutation score: ${killed}/${Object.keys(versions).length - 1}`);",
          task: "Two mutants survive with full line coverage. Add the fewest tests that kill all five. Then write a sixth mutant your suite still misses.",
        },
        { t: "say", h: "Coverage counts execution, not checking", x: "Coverage says which lines ran, not which results were checked. **Mutation testing** asks the real question: break the code in small ways and count how many breaks your suite notices. StrykerJS automates it for JS." },
        {
          t: "pitfall",
          h: "A test you never saw fail is untested",
          x: "Classic silent passes: an `expect` inside a callback that never runs, a promise assertion without `await`, an `expect(x)` with no matcher after it. Once per new test, break the code on purpose and watch it go red. Ten seconds, and you know the wiring works.",
        },
        {
          t: "quiz",
          q: "Which test has the worst confidence per minute of upkeep?",
          options: ["A unit test of a date parser with 12 edge cases", "A test asserting a component calls three internal helpers in order", "One e2e test of signup and first login", "A property test that encode then decode returns the input"],
          answer: 1,
          why: "It breaks on every refactor and passes when the output is wrong, so it costs the most and proves the least. The parser and round-trip tests pin behaviour cheaply; the e2e test is slow but guards the money path.",
        },
      ],
    },
    {
      title: "Choosing the level",
      beats: [
        {
          t: "table",
          head: ["Level", "Proves", "Cost per run", "Breaks when"],
          rows: [
            ["Unit", "One function's logic, edge cases", "ms", "Its signature changes"],
            ["Integration", "Your modules work together with real wiring", "10s of ms", "Behaviour of the slice changes"],
            ["Component", "A UI piece renders and responds to a user, in jsdom or a real browser", "10s to 100s of ms", "What the user sees or does changes"],
            ["End-to-end", "The deployed stack works through a real browser", "seconds", "Anything, including the network"],
          ],
        },
        { t: "say", x: "The **pyramid** says mostly unit tests. The **testing trophy** says mostly integration, because that's where bugs live: at the joins. Both are heuristics. The real rule: test at the lowest level that can see the bug you fear." },
        {
          t: "quiz",
          q: "Frontend tests mock the API as `{ price }`. Backend tests assert the API returns `{ priceCents }`. Both suites are green. What catches this?",
          options: ["More frontend unit tests", "More backend unit tests", "Something that crosses the boundary: an e2e test, a contract test, or one shared schema both sides import", "100% coverage on both"],
          answer: 2,
          why: "Each side tests against its own belief about the other. Mocks freeze that belief. Only a test or a type that spans both sides can notice they disagree.",
        },
        {
          t: "pitfall",
          h: "Mock at the network edge, not your own modules",
          x: "Mock `./api.js` and the code that builds URLs, headers and parses JSON never runs in tests. Intercept the request instead (a request-level mock like MSW) so your real fetch code runs and only the server is fake.",
        },
        {
          t: "steps",
          h: "Picking a level for a new feature",
          items: [
            "Name the bug you're most afraid of shipping.",
            "Find the lowest level where that bug is visible: a pure function, a component, or the whole stack.",
            "Write that test first and see it fail.",
            "Pure logic with many edge cases: unit tests, or a property test.",
            "One e2e test per money path (signup, checkout), not per feature.",
          ],
        },
      ],
    },
    {
      title: "Tests that survive refactors",
      beats: [
        { t: "say", x: "A good test fails when behaviour breaks and **only then**. So test through the interface your caller touches: for a function, its arguments and return value; for a UI, what a user can see and do." },
        {
          t: "compare",
          a: { label: "Implementation detail", lang: "jsx", src: "test(\"saves\", async () => {\n  const { container } = render(<Editor />);\n  const btn = container.querySelector(\".btn-primary\");\n  fireEvent.click(btn);\n  expect(mockSetSaving).toHaveBeenCalledWith(true);\n  expect(container.querySelector(\".toast\")).not.toBeNull();\n});" },
          b: { label: "Behaviour", lang: "jsx", src: "test(\"saves\", async () => {\n  const user = userEvent.setup();\n  render(<Editor />);\n  await user.click(screen.getByRole(\"button\", { name: /save/i }));\n  expect(await screen.findByRole(\"status\"))\n    .toHaveTextContent(\"Saved\");\n});" },
          x: "Left breaks when you rename a class or swap `useState` for a reducer, and passes if the button stops working for keyboard users. Right only cares about the role and the words the user sees.",
        },
        {
          t: "table",
          head: ["Query", "When nothing matches", "Use it for"],
          rows: [
            ["`getBy...`", "Throws at once", "Something that must be there now"],
            ["`queryBy...`", "Returns `null`", "Asserting absence"],
            ["`findBy...`", "Returns a promise, retries, rejects after 1000 ms", "Something that appears after async work"],
          ],
          caption: "Prefer ByRole, then ByLabelText, then ByText. ByTestId is the last resort, for things a user can't perceive.",
        },
        {
          t: "predict",
          lang: "jsx",
          src: "render(<Editor />);   // the \"Saved\" message is not shown yet\n\nexpect(screen.getByText(\"Saved\")).not.toBeInTheDocument();",
          q: "What happens?",
          options: ["Passes", "Fails, because `getByText` throws before `expect` runs", "Passes after waiting 1000 ms", "Fails with a type error"],
          answer: 1,
          why: "`getBy` throws when nothing matches, so the test errors on the line that was meant to assert absence. Use `expect(screen.queryByText(\"Saved\")).not.toBeInTheDocument()`.",
        },
        {
          t: "pitfall",
          h: "If ByRole can't find it, neither can a screen reader",
          x: "`getByRole(\"button\")` fails on a `<div onClick>` because a div has no button role, can't be focused and ignores Enter. When a role query won't match, the fix is usually the markup, not the query. The test just filed an accessibility bug.",
        },
        {
          t: "quiz",
          q: "You move a form's state from component state into a store. Which tests should break?",
          options: ["Tests that type, submit and check the result", "Tests that read component state or assert a setter was called", "All of them", "None, the store is mocked anyway"],
          answer: 1,
          why: "Behaviour didn't change, so behaviour tests stay green, which is how you know the refactor is safe. Tests coupled to where the state lives are noise: they fail on a correct change.",
        },
      ],
    },
    {
      title: "Vitest essentials",
      beats: [
        {
          t: "code",
          lang: "js",
          file: "checkout.test.js",
          src: "import { test, expect, vi, afterEach } from \"vitest\";\nimport { sendReceipt } from \"./checkout.js\";\n\nafterEach(() => vi.restoreAllMocks());   // put spyOn'd methods back\n\ntest(\"emails a receipt once, with the order total\", async () => {\n  const mailer = { send: vi.fn().mockResolvedValue({ id: \"m1\" }) };   // a stub you hand in\n  const log = vi.spyOn(console, \"warn\").mockImplementation(() => {}); // a spy on a real method\n\n  await sendReceipt({ id: 7, total: 4200 }, mailer);\n\n  expect(mailer.send).toHaveBeenCalledTimes(1);\n  expect(mailer.send).toHaveBeenCalledWith(\n    expect.objectContaining({ subject: expect.stringContaining(\"#7\") }),\n  );\n  expect(log).not.toHaveBeenCalled();\n});",
          note: "`vi.fn()` makes a function that records calls. `vi.spyOn` wraps a real method. Pass collaborators in as arguments and most tests need no module mocking at all.",
        },
        {
          t: "predict",
          lang: "js",
          src: "const sleep = (ms) => new Promise((r) => setTimeout(r, ms));\nasync function poll(fetchA) { await fetchA(); await sleep(1000); await fetchA(); }\n\ntest(\"polls twice\", () => {\n  vi.useFakeTimers();\n  const fetchA = vi.fn().mockResolvedValue(\"ok\");\n  poll(fetchA);\n  vi.advanceTimersByTime(1000);\n  expect(fetchA).toHaveBeenCalledTimes(2);\n});",
          q: "Does the test pass?",
          options: ["Yes, 1000 ms passed", "No: fetchA was called once, because the sleep timer didn't exist yet", "No: fake timers break promises", "It hangs forever"],
          answer: 1,
          why: "`advanceTimersByTime` runs synchronously. The first `await` hasn't resumed, so `sleep` hasn't scheduled its timer. `await vi.advanceTimersByTimeAsync(1000)` lets microtasks run between timers, and the test passes.",
        },
        {
          t: "play",
          mode: "js",
          title: "a fake clock in 20 lines",
          js: "// A fake clock is a priority queue of timers and a number called \"now\".\nfunction fakeClock() {\n  let now = 0, seq = 0;\n  const timers = new Map();                       // id -> { at, fn }\n  return {\n    setTimeout(fn, ms) { timers.set(++seq, { at: now + ms, fn }); return seq; },\n    clearTimeout(id) { timers.delete(id); },\n    tick(ms) {                                    // run due timers in time order\n      const end = now + ms;\n      for (;;) {\n        let next = null;\n        for (const [id, t] of timers) if (t.at <= end && (!next || t.at < next[1].at)) next = [id, t];\n        if (!next) break;\n        timers.delete(next[0]);\n        now = next[1].at;\n        next[1].fn();\n      }\n      now = end;\n    },\n  };\n}\n\n// Code under test takes its clock as a parameter instead of reaching for globals.\nfunction debounce(fn, ms, clock = globalThis) {\n  let id;\n  return (...args) => { clock.clearTimeout(id); id = clock.setTimeout(() => fn(...args), ms); };\n}\n\nconst clock = fakeClock();\nconst calls = [];\nconst save = debounce((q) => calls.push(q), 300, clock);\n\nsave(\"r\"); clock.tick(100);\nsave(\"re\"); clock.tick(100);\nsave(\"rea\"); clock.tick(299);\nconsole.log(\"after 499 ms:\", calls);   // nothing yet: the last call reset the timer\nclock.tick(1);\nconsole.log(\"after 500 ms:\", calls);   // fires once, with the last value",
          task: "Add `setInterval` to the fake clock, then make `tick` throw after 10,000 timers in one call, the way real fake-timer libraries stop runaway intervals.",
        },
        {
          t: "table",
          head: ["Vitest", "What it does"],
          rows: [
            ["`vi.useFakeTimers()`", "Fakes setTimeout, setInterval, setImmediate, their clears, and Date"],
            ["`vi.advanceTimersByTime(ms)`", "Runs due timers synchronously; no microtasks in between"],
            ["`vi.advanceTimersByTimeAsync(ms)`", "Same, but awaits between timers, so promise chains progress"],
            ["`vi.runAllTimers()`", "Runs until the queue is empty; throws after 10,000 timers"],
            ["`vi.setSystemTime(date)`", "Moves `Date.now()` and `new Date()` without firing timers"],
            ["`vi.useRealTimers()`", "Put it in `afterEach`, or the next test inherits a frozen clock"],
          ],
          caption: "`process.nextTick` and `queueMicrotask` are not faked unless you list them in `toFake`.",
        },
        {
          t: "pitfall",
          h: "`vi.mock` runs before your variables exist",
          x: "Vitest moves every `vi.mock` call to the top of the file, above your imports and constants. A factory that reads a top-level `const` during the mock throws `Cannot access 'fake' before initialization`. Declare shared values with `vi.hoisted`.",
        },
        { t: "code", lang: "js", src: "import { vi, test, expect } from \"vitest\";\nimport { getUser } from \"./api.js\";\n\n// const fake = { id: 1, name: \"Ada\" };   // ReferenceError: vi.mock runs before this line\nconst { fake } = vi.hoisted(() => ({ fake: { id: 1, name: \"Ada\" } }));\n\nvi.mock(\"./api.js\", () => ({ getUser: vi.fn().mockResolvedValue(fake) }));\n\ntest(\"uses the mocked module\", async () => {\n  expect(await getUser(1)).toEqual(fake);\n});", mark: [5] },
        {
          t: "pitfall",
          h: "Over-mocking tests your mocks",
          x: "Mock the db, the mailer and the logger, then assert each was called with the right arguments, and you've written the implementation twice. The test passes when the real mailer's API changes, because the mock still has the old shape. Mock what's slow or outside your control, nothing else.",
        },
      ],
    },
    {
      title: "Playwright without flakes",
      beats: [
        { t: "code", lang: "js", file: "checkout.spec.js", src: "import { test, expect } from \"@playwright/test\";\n\ntest(\"checkout shows the order number\", async ({ page }) => {\n  await page.goto(\"/cart\");\n  await page.getByRole(\"button\", { name: \"Place order\" }).click();   // waits until actionable\n\n  // web-first assertions retry until they pass or time out (5 s by default)\n  await expect(page.getByRole(\"heading\", { name: /order #\\d+/i })).toBeVisible();\n  await expect(page.getByRole(\"status\")).toHaveText(\"Payment received\");\n});", note: "Locators are lazy queries, re-run on every attempt. They never hold a stale element the way a saved DOM node does." },
        { t: "say", h: "Auto-waiting", x: "Before `click()`, Playwright waits until the element is visible, stable (not animating), receives events (nothing on top) and enabled. Assertions like `toBeVisible` retry until they pass or time out. You state the end condition; it does the polling." },
        {
          t: "compare",
          a: { label: "Sleep and hope", lang: "js", src: "await page.getByRole(\"button\", { name: \"Save\" }).click();\nawait page.waitForTimeout(2000);\nexpect(await page.locator(\".toast\").textContent())\n  .toBe(\"Saved\");" },
          b: { label: "Wait for the condition", lang: "js", src: "await page.getByRole(\"button\", { name: \"Save\" }).click();\nawait expect(page.getByRole(\"status\"))\n  .toHaveText(\"Saved\");" },
          x: "The sleep is too long on your laptop (2 s wasted every run) and too short on a loaded CI runner (red). The assertion returns the moment the text appears and waits up to the timeout when it's slow.",
        },
        {
          t: "predict",
          lang: "js",
          src: "await page.getByRole(\"button\", { name: \"Save\" }).click();\n// the toast appears after the save request returns\nexpect(await page.getByRole(\"status\").isVisible()).toBe(true);",
          q: "Is this flaky?",
          options: ["No, Playwright auto-waits", "Yes: `isVisible()` checks once and returns at once; only actions and `expect(locator)` assertions wait", "Only in Firefox", "No, the click waits for the request"],
          answer: 1,
          why: "`isVisible()` is a snapshot, and the click only waits until the click is done, not for the network. Pass on a fast machine, fail on a slow one. `await expect(locator).toBeVisible()` retries.",
        },
        {
          t: "table",
          head: ["Cause", "Symptom", "Fix"],
          rows: [
            ["Time", "Fails near midnight, month ends, DST, or in another timezone", "Fake the clock; set TZ in the test config"],
            ["Order", "Passes alone, fails in the full run", "Each test builds its own state; run with `--sequence.shuffle`"],
            ["Shared state", "Fails when parallel workers run", "Unique data per test: new user, new id, own db schema"],
            ["Network", "Fails when a third-party API is slow", "Mock external services; only your stack is real"],
            ["Animation", "Click lands on the old position or an overlay", "Assert the end state; disable motion in tests"],
            ["Sleeps", "Fails only on CI", "Replace every fixed wait with a waiting assertion"],
          ],
        },
        {
          t: "predict",
          lang: "js",
          src: "// formatDue(date) -> \"today\" | \"tomorrow\" | \"in N days\"\ntest(\"a task due tomorrow says tomorrow\", () => {\n  const due = new Date(Date.now() + 24 * 60 * 60 * 1000);\n  expect(formatDue(due)).toBe(\"tomorrow\");\n});",
          q: "Is this flaky?",
          options: ["No, it's deterministic", "Yes: it can fail across a DST change, where a calendar day isn't 24 hours", "Only on Windows", "Only if formatDue is async"],
          answer: 1,
          why: "If tomorrow has only 23 hours, 23:30 plus 24 hours lands two calendar days later. Two nights a year, red, then green on rerun. Pin the clock with `vi.setSystemTime` and build dates from calendar parts.",
        },
        { t: "code", lang: "js", src: "// playwright.config.js\nimport { defineConfig } from \"@playwright/test\";\n\nexport default defineConfig({\n  retries: process.env.CI ? 2 : 0,\n  use: {\n    baseURL: \"http://localhost:5173\",\n    trace: \"on-first-retry\",   // DOM snapshots, network, console for the failed run\n  },\n});\n\n// npx playwright test --repeat-each=50 checkout.spec.js   hunt a flake locally\n// npx playwright show-trace test-results/.../trace.zip   replay it step by step", note: "A trace records every action with DOM snapshots before and after, network and console. Read the trace before you touch the test." },
        {
          t: "pitfall",
          h: "Retries turn flakes into a slow lie",
          x: "Retries make CI green and hide the cause: maybe a real race your users also hit. Playwright marks tests that pass on retry as flaky; track that list and fix it weekly. A quarantined test with no owner and no date is a deleted test.",
        },
      ],
    },
    {
      title: "Properties and brute force",
      beats: [
        { t: "say", x: "You already know this from contests: write a brute force, generate small random inputs, compare, shrink the failing case. **Property-based testing** is that habit as a library. You state what's always true; it hunts for a counterexample." },
        { t: "code", lang: "js", file: "sort.test.js", src: "import { expect } from \"vitest\";\nimport { test, fc } from \"@fast-check/vitest\";\nimport { mySort } from \"./sort.js\";\n\nconst ints = fc.array(fc.integer());\n\ntest.prop([ints])(\"output is sorted\", (a) => {\n  const s = mySort(a);\n  for (let i = 1; i < s.length; i++) expect(s[i - 1]).toBeLessThanOrEqual(s[i]);\n});\n\ntest.prop([ints])(\"output is a permutation of the input\", (a) => {\n  const count = (xs) => xs.reduce((m, x) => m.set(x, (m.get(x) ?? 0) + 1), new Map());\n  expect(count(mySort(a))).toEqual(count(a));\n});\n\ntest.prop([ints])(\"sorting twice changes nothing\", (a) => {\n  expect(mySort(mySort(a))).toEqual(mySort(a));\n});", note: "`@fast-check/vitest` gives `test.prop`. One property catches nothing alone: `[]` is sorted. Sorted plus permutation pins sorting down completely." },
        {
          t: "table",
          head: ["Property", "Example"],
          rows: [
            ["Round trip", "`decode(encode(x))` equals `x`"],
            ["Oracle", "Fast version equals brute force on small inputs"],
            ["Invariant", "Output sorted, same multiset as the input"],
            ["Idempotence", "`format(format(x))` equals `format(x)`"],
            ["Metamorphic", "Adding a filter never returns more rows"],
            ["Never crashes", "Any string into the parser: an error value, never a throw"],
          ],
        },
        {
          t: "play",
          mode: "js",
          title: "differential testing: LIS vs brute force",
          js: "// Fast: longest strictly increasing subsequence, O(n log n). One character is wrong.\nfunction lisFast(a) {\n  const tails = [];\n  for (const x of a) {\n    let lo = 0, hi = tails.length;\n    while (lo < hi) { const m = (lo + hi) >> 1; if (tails[m] <= x) lo = m + 1; else hi = m; }\n    tails[lo] = x;\n  }\n  return tails.length;\n}\n// Slow but obviously right: try every subsequence. Fine for n <= 12.\nfunction lisBrute(a) {\n  let best = 0;\n  for (let mask = 0; mask < 1 << a.length; mask++) {\n    let last = -Infinity, len = 0, ok = true;\n    for (let i = 0; i < a.length && ok; i++) if (mask >> i & 1) { ok = a[i] > last; last = a[i]; len++; }\n    if (ok) best = Math.max(best, len);\n  }\n  return best;\n}\nconst randArr = () => Array.from({ length: Math.random() * 9 | 0 }, () => Math.random() * 5 | 0);\nconst fails = (a) => lisFast(a) !== lisBrute(a);\n// Shrink: keep deleting one element, or lowering one value, while it still fails.\nfunction shrink(a) {\n  for (let changed = true; changed; ) {\n    changed = false;\n    const cands = [...a.map((_, i) => a.filter((_, j) => j !== i)), ...a.flatMap((v, i) => (v > 0 ? [a.with(i, v - 1)] : []))];\n    for (const c of cands) if (fails(c)) { a = c; changed = true; break; }\n  }\n  return a;\n}\nfor (let run = 1; run <= 1000; run++) {\n  const a = randArr();\n  if (fails(a)) {\n    const s = shrink(a);\n    console.log(`run ${run}: failed on [${a}]`);\n    console.log(`shrunk to [${s}]: fast says ${lisFast(s)}, brute says ${lisBrute(s)}`);\n    break;\n  }\n  if (run === 1000) console.log(\"1000 random cases agree\");\n}",
          task: "Add a shrink step that lowers every element at once and watch a pair like `[4,4]` become `[0,0]`. Then fix the one-character bug so 1000 cases agree.",
        },
        {
          t: "predict",
          lang: "text",
          src: "// mySort = (a) => [...a].sort()   (no comparator)\nProperty failed after 2 tests\n{ seed: 1704661133, path: \"1:3:2:3:1:2:2:...\", endOnFailure: true }\nCounterexample: [[2,1000000000]]\nShrunk 85 time(s)",
          q: "`[10, 2]` also fails and is smaller. Why did fast-check stop at `[2, 1000000000]`?",
          options: ["A bug in fast-check", "Shrinking is a greedy local search: it stops when no single shrink step still fails, which is a local minimum", "It ran out of time", "Large numbers are what fails"],
          answer: 1,
          why: "Each step tries smaller candidates and keeps the first that still fails. From `[2, 1e9]` no one step does, so it stops. Small is guaranteed; smallest isn't. Rerun with another seed and you may get `[10, 2]`.",
        },
        {
          t: "pitfall",
          h: "A random failure you can't replay is noise",
          x: "Every fast-check failure prints a `seed` and `path`. Pass them back with `fc.assert(prop, { seed, path })` to replay exactly that case. Then copy the shrunk counterexample into a plain example test so it stays fixed forever.",
        },
        {
          t: "quiz",
          q: "Which property, alone, would a broken sort pass most easily?",
          options: ["Output is sorted", "Output has the same elements as input", "Output equals the brute-force sort", "Sorted and same elements"],
          answer: 0,
          why: "`() => []` is sorted. The oracle and the combined property both pin the answer exactly; same-elements alone passes the identity function. Pairs of weak properties often make one strong one.",
        },
      ],
    },
    {
      title: "Snapshots, pixels and axe",
      beats: [
        {
          t: "compare",
          a: { label: "Snapshot of everything", lang: "jsx", src: "test(\"renders\", () => {\n  const { container } = render(<InvoicePage />);\n  expect(container).toMatchSnapshot();\n  // __snapshots__: 1,480 lines of markup,\n  // reviewed by nobody, updated with -u\n  // whenever anything changes\n});" },
          b: { label: "Assert what matters", lang: "jsx", src: "test(\"overdue invoices are flagged\", () => {\n  render(<InvoicePage invoices={[overdue]} />);\n  const row = screen.getByRole(\"row\", { name: /INV-17/ });\n  expect(within(row).getByText(\"Overdue\"))\n    .toBeInTheDocument();\n  expect(formatAmount(1999, \"EUR\"))\n    .toMatchInlineSnapshot(`\"€19.99\"`);\n});" },
          x: "A big snapshot fails on every harmless change, so people learn to press `u`. Small inline snapshots of a value you care about stay readable in the diff.",
        },
        {
          t: "pitfall",
          h: "Snapshot rot",
          x: "A snapshot that nobody reads gets updated with `vitest -u` whenever it fails, which means it fails on nothing. If a reviewer can't tell from the diff whether the change is right, delete the snapshot and write the two assertions it was standing in for.",
        },
        { t: "code", lang: "js", file: "pricing.spec.js", src: "import { test, expect } from \"@playwright/test\";\nimport AxeBuilder from \"@axe-core/playwright\";\n\ntest(\"pricing page\", async ({ page }) => {\n  await page.goto(\"/pricing\");\n\n  // pixels: compares with a stored baseline; animations are frozen by default\n  await expect(page).toHaveScreenshot(\"pricing.png\", {\n    mask: [page.getByTestId(\"live-price\")],   // paint over what changes every run\n    maxDiffPixelRatio: 0.01,\n  });\n\n  // accessibility: machine-checkable WCAG rules only\n  const results = await new AxeBuilder({ page })\n    .withTags([\"wcag2a\", \"wcag2aa\"])\n    .analyze();\n  expect(results.violations).toEqual([]);\n});", note: "The first run writes the baseline and fails. Review it, commit it. Later runs compare against it; `--update-snapshots` rewrites it." },
        {
          t: "pitfall",
          h: "Baselines are per OS, browser and font stack",
          x: "Font hinting differs between macOS and Linux, so a baseline made on your laptop fails on CI by a few hundred pixels. Playwright names files per browser and platform. Generate and update baselines in the same container CI runs.",
        },
        {
          t: "quiz",
          q: "axe reports zero violations. What can still be broken?",
          options: ["Nothing, axe covers WCAG", "Missing button names", "Alt text that's present but wrong, focus order that makes no sense, a keyboard trap in a custom widget", "Colour contrast"],
          answer: 2,
          why: "axe checks what a machine can decide: missing names, contrast, bad ARIA. It can't judge whether the alt text describes the image or the tab order matches the layout. Tab through the page yourself.",
        },
        {
          t: "steps",
          h: "Tests in CI, cheapest first",
          items: [
            "Lint and type-check: seconds, catch the dumbest bugs.",
            "Unit and integration tests, in parallel.",
            "Build once; run e2e against that exact build, sharded across machines.",
            "Upload traces and screenshot diffs as artifacts on failure.",
            "Block merges on red. The workflow file itself belongs in GitHub and CI.",
          ],
        },
      ],
    },
    {
      title: "Honest numbers",
      beats: [
        { t: "say", x: "A benchmark is an experiment, and most published microbenchmarks measure something other than what they claim: the JIT warming up, the timer's resolution, a GC pause, or code the compiler deleted." },
        {
          t: "predict",
          lang: "js",
          src: "function f(a) { return a.reduce((s, x) => s + x, 0); }\nconst data = Array.from({ length: 100000 }, (_, i) => i % 1000);\n\nfor (let run = 1; run <= 3; run++) {\n  const t0 = performance.now();\n  f(data);\n  console.log(run, (performance.now() - t0).toFixed(3), \"ms\");\n}",
          q: "Run 1 is often the slowest. Why?",
          options: ["The array is copied on first use", "The first calls run in the interpreter or baseline tier; V8 optimises the function once it's hot", "performance.now is slow the first time", "Garbage collection always runs first"],
          answer: 1,
          why: "V8 starts in the Ignition interpreter and tiers up to optimised code after enough calls. Time cold runs and you measure the compiler. Discard warm-up runs, then sample.",
        },
        {
          t: "play",
          mode: "js",
          title: "a benchmark that tells the truth",
          js: "const data = Array.from({ length: 100000 }, (_, i) => (i * 7919) % 1000);\nconst impls = {\n  loop: (a) => { let s = 0; for (let i = 0; i < a.length; i++) s += a[i]; return s; },\n  reduce: (a) => a.reduce((s, x) => s + x, 0),\n};\nlet sink = 0;                                   // use every result, or the JIT may delete the work\n\nfunction sample(fn, reps = 20) {                // one sample = reps calls, so timer resolution doesn't dominate\n  const t0 = performance.now();\n  for (let r = 0; r < reps; r++) sink += fn(data);\n  return (performance.now() - t0) / reps;\n}\nconst pct = (xs, p) => { const s = [...xs].sort((a, b) => a - b); return s[Math.min(s.length - 1, Math.floor(p * s.length))]; };\nconst f = (ms) => ms.toFixed(3) + \" ms\";\n\n// 1. Warm-up is visible: the first samples run before the JIT has optimised the function.\nconst cold = Array.from({ length: 8 }, () => sample(impls.reduce, 1));\nconsole.log(\"reduce, first 8 calls:\", cold.map(f).join(\" \"));\n\n// 2. Interleave A and B so drift (thermal, GC, other tabs) hits both equally.\nconst res = { loop: [], reduce: [] };\nfor (let i = 0; i < 30; i++) for (const k of Object.keys(impls)) sample(impls[k]);   // warm-up, discarded\nfor (let i = 0; i < 100; i++) for (const k of Object.keys(impls)) res[k].push(sample(impls[k]));\n\nfor (const [k, xs] of Object.entries(res))\n  console.log(`${k.padEnd(6)} n=${xs.length}  min ${f(Math.min(...xs))}  p50 ${f(pct(xs, 0.5))}  p95 ${f(pct(xs, 0.95))}`);\nconst ratio = pct(res.reduce, 0.5) / pct(res.loop, 0.5);\nconsole.log(`median ratio reduce/loop: ${ratio.toFixed(2)}x  (sink ${sink % 10})`);\nconsole.log(\"Run it 3 times. If the ratio moves more than the gap, you have no result.\");",
          task: "Run it three times and write down the ratio each time. Then swap the order of `loop` and `reduce` in `impls` and see whether the ratio moves.",
        },
        {
          t: "table",
          head: ["Mistake", "What you measured instead"],
          rows: [
            ["No warm-up", "The JIT compiling your function"],
            ["One run", "Whatever the OS scheduler did at that moment"],
            ["Mean only", "Your GC pauses, averaged into everything"],
            ["Unused result", "An empty loop: the optimiser may drop the work"],
            ["Different inputs for A and B", "The inputs"],
            ["All of A, then all of B", "Thermal throttling and background tabs, blamed on B"],
            ["Tiny n, then p99", "The maximum, with a fancy name"],
          ],
        },
        {
          t: "quiz",
          q: "Three runs each. A: 100, 104, 98 ms. B: 95, 110, 92 ms. What can you claim?",
          options: ["B is 1.7% faster", "B is faster on average", "No difference shown: the spread within each is larger than the gap between them", "A is more reliable, so A is faster"],
          answer: 2,
          why: "Means of 100.7 and 99 with ranges of 6 and 18 ms. Noise is bigger than signal. Take more samples, compare medians, and only claim a gap that survives repeated runs.",
        },
        {
          t: "compare",
          a: { label: "Overstated", lang: "text", src: "Rewrote the parser in WASM. It's 3x faster." },
          b: { label: "Defensible", lang: "text", src: "Parsing a 2 MB JSON log: median 41 ms -> 14 ms\n(n=200 runs each, after 20 warm-up runs, p95 58 -> 19 ms).\nNode 22, M2 laptop on power, same input, interleaved A/B.\nNot tested: inputs under 10 KB (WASM call overhead may\ndominate), Safari, cold start including WASM compile." },
          x: "The right one names the input, n, warm-up, percentiles, machine and method, and says where the result might not hold. It sounds less exciting and is believed more.",
        },
        {
          t: "pitfall",
          h: "'Faster' without the input size is a guess",
          x: "A rewrite that wins at n = 10^6 often loses at n = 10, where call overhead dominates. Report the size you measured, and if the claim matters, sweep sizes and plot them. Crossovers are where the interesting decisions are.",
        },
        { t: "say", h: "State what you didn't test", x: "Every result has edges: browsers you skipped, input sizes, cold starts, the slow phone. Writing them down costs a line and saves a reader from trusting a number past where it holds. Profiling itself lives in Performance and robustness." },
        {
          t: "mission",
          h: "Hunt one flake to its cause",
          x: "Take a suite you own. Run it with `--repeat-each=30` (Playwright) or `--sequence.shuffle` plus `--repeats` (Vitest) until something fails. Find the cause in the trace or by bisecting order, fix the cause, not the timeout. Write three lines: cause, fix, what you didn't check.",
          hint: "Failures only in the full run point to order or shared state. Failures only on CI point to time, sleeps or CPU. Debugging like a pro covers narrowing it down.",
        },
      ],
    },
    {
      title: "Rebuild: a test runner",
      beats: [
        { t: "say", x: "A test runner does two passes. First it **collects**: `describe` runs its body at once, `it` only records a function. Then it **runs**: each test inside try/catch, awaited, with hooks in front. That's the whole trick." },
        {
          t: "rebuild",
          h: "describe, it, expect in 40 lines",
          x: "`describe` builds a tree of suites, `it` records tests, `beforeEach` stacks hooks from outer to inner, `run` walks the tree and awaits each test. A failing `expect` is just a thrown Error. One test fails on purpose.",
          mode: "js",
          js: "// A test runner: collect first, run later. describe/it only register; run() executes.\nconst root = { name: \"\", tests: [], children: [], beforeEach: [] };\nlet current = root;\nfunction describe(name, body) {\n  const suite = { name, tests: [], children: [], beforeEach: [], parent: current };\n  current.children.push(suite);\n  current = suite; body(); current = suite.parent;           // body runs now, tests run later\n}\nconst it = (name, fn) => current.tests.push({ name, fn });\nconst beforeEach = (fn) => current.beforeEach.push(fn);\n\nfunction expect(actual) {\n  const fail = (msg) => { throw new Error(msg); };\n  const show = (v) => JSON.stringify(v);\n  return {\n    toBe: (exp) => Object.is(actual, exp) || fail(`expected ${show(actual)} to be ${show(exp)}`),\n    toEqual: (exp) => show(actual) === show(exp) || fail(`expected ${show(actual)} to equal ${show(exp)}`),\n    toThrow: () => { try { actual(); } catch { return; } fail(\"expected function to throw\"); },\n  };\n}\n\nasync function run(suite = root, path = [], hooks = [], stats = { pass: 0, fail: 0 }) {\n  const names = suite.name ? [...path, suite.name] : path;\n  const allHooks = [...hooks, ...suite.beforeEach];          // outer hooks run first\n  for (const t of suite.tests) {\n    const label = [...names, t.name].join(\" > \");\n    try {\n      for (const h of allHooks) await h();\n      await t.fn();                                          // async tests just work\n      stats.pass++; console.log(\"  pass\", label);\n    } catch (e) {\n      stats.fail++; console.log(\"  FAIL\", label, \"\\n       \" + e.message);\n    }\n  }\n  for (const child of suite.children) await run(child, names, allHooks, stats);\n  if (suite === root) console.log(`${stats.pass} passed, ${stats.fail} failed`);\n}\n\n// ---- a test file ----\ndescribe(\"stack\", () => {\n  let s;\n  beforeEach(() => { s = []; });\n  it(\"starts empty\", () => expect(s.length).toBe(0));\n  it(\"pops what it pushed\", () => { s.push(1, 2); expect(s.pop()).toBe(2); });\n  describe(\"async\", () => {\n    it(\"waits for promises\", async () => {\n      const v = await new Promise((r) => setTimeout(() => r([1, 2]), 50));\n      expect(v).toEqual([1, 2]);\n    });\n    it(\"reports a failure\", () => expect([1, 2].map(String)).toEqual([1, 2]));\n  });\n});\nrun();",
          task: "Add `it.only` (if any test is marked, run only those) and a per-test timeout using `Promise.race`. Then add `afterEach`.",
        },
        {
          t: "quiz",
          q: "In the runner, a test calls `setTimeout(() => expect(1).toBe(2), 10)` and returns nothing. What happens?",
          options: ["It fails", "It passes, and the error is thrown later outside any test", "The runner waits 10 ms", "A syntax error"],
          answer: 1,
          why: "The test returns undefined, so it counts as passed at once. The throw happens later in a timer, outside the try/catch. Real runners catch it as an unhandled error; the fix is the same: return or await a promise.",
        },
        {
          t: "mission",
          h: "A property tester with shrinking",
          x: "Build `check(arbitrary, property)`. An arbitrary has `gen(rnd)` and `shrink(value)` that yields smaller values. Use a seeded PRNG and print the seed on failure. Shrink greedily. Find the default-sort bug with it.",
          hint: "Integers shrink toward 0: yield 0, the halfway point, then one step closer. Arrays shrink by removing one element, then by shrinking one element. Keep the first candidate that still fails.",
          solution: { lang: "js", src: "// An arbitrary = how to generate a value + how to list smaller ones.\nconst int = (lo, hi) => ({\n  gen: (rnd) => lo + Math.floor(rnd() * (hi - lo + 1)),\n  *shrink(v) { const t = lo <= 0 && 0 <= hi ? 0 : lo; if (v !== t) { yield t; yield t + Math.trunc((v - t) / 2); yield v - Math.sign(v - t); } },\n});\nconst array = (item, maxLen = 20) => ({\n  gen: (rnd) => Array.from({ length: Math.floor(rnd() * (maxLen + 1)) }, () => item.gen(rnd)),\n  *shrink(a) {\n    for (let i = 0; i < a.length; i++) yield [...a.slice(0, i), ...a.slice(i + 1)];\n    for (let i = 0; i < a.length; i++) for (const s of item.shrink(a[i])) yield a.with(i, s);\n  },\n});\nfunction mulberry32(seed) {                       // seeded PRNG so failures replay\n  return () => { seed = (seed + 0x6d2b79f5) | 0; let t = seed;\n    t = Math.imul(t ^ (t >>> 15), t | 1); t ^= t + Math.imul(t ^ (t >>> 7), t | 61);\n    return ((t ^ (t >>> 14)) >>> 0) / 4294967296; };\n}\nfunction check(arb, prop, { runs = 200, seed = Date.now() } = {}) {\n  const rnd = mulberry32(seed), holds = (v) => { try { return prop(v) !== false; } catch { return false; } };\n  for (let i = 0; i < runs; i++) {\n    let v = arb.gen(rnd);\n    if (holds(v)) continue;\n    let steps = 0;\n    for (let again = true; again; ) {             // greedy: take the first smaller value that still fails\n      again = false;\n      for (const s of arb.shrink(v)) if (!holds(s)) { v = s; steps++; again = true; break; }\n    }\n    return console.log(`failed (seed ${seed}, run ${i + 1}), shrunk ${steps}x to`, JSON.stringify(v));\n  }\n  console.log(`ok, ${runs} runs`);\n}\ncheck(array(int(-1000, 1000)), (a) => { const s = [...a].sort(); return s.every((x, i) => i === 0 || s[i - 1] <= x); });\ncheck(array(int(-1000, 1000)), (a) => { const s = [...a].sort((x, y) => x - y); return s.every((x, i) => i === 0 || s[i - 1] <= x); });" },
        },
      ],
    },
  ],
  nobodyTells: [
    "Break the code on purpose once for every new test. A test you never saw fail may be asserting nothing.",
    "Coverage tells you what ran, not what was checked. Mutation score is the number that means something.",
    "If `getByRole` can't find your button, a screen reader can't either. Fix the markup, not the query.",
    "Every `waitForTimeout` in an e2e suite is a future flake. Wait for a condition instead.",
    "Retries hide flakes. Track the tests that pass on retry and treat that list as a bug queue.",
    "Your contest stress-test habit, brute force plus random small inputs, is the best testing technique most web devs never use.",
    "Copy every shrunk counterexample into a plain example test. Random tests find bugs; example tests keep them fixed.",
    "Report medians and n, interleave A and B, and say which inputs you didn't try. Then the number is worth quoting.",
  ],
  glossary: [
    ["mutation testing", "Planting small bugs in code and counting how many your tests catch. Survivors show what's unchecked."],
    ["testing trophy", "A test mix weighted toward integration tests, with fewer unit and e2e tests at the edges."],
    ["stub", "A stand-in function that returns canned values so the code under test can run."],
    ["spy", "A wrapper that records calls to a real or fake function so a test can inspect them."],
    ["fake timers", "A replaced clock where time moves only when the test advances it."],
    ["auto-waiting", "Playwright's checks that an element is visible, stable, enabled and unobscured before acting."],
    ["web-first assertion", "A Playwright `expect` on a locator that retries until it passes or times out."],
    ["flaky test", "A test that passes and fails on the same code. It is a bug, either in the test or the product."],
    ["property-based testing", "Generating many inputs and checking a rule that must hold for all of them."],
    ["shrinking", "Reducing a failing input to a small one that still fails. Greedy, so a local minimum."],
    ["differential testing", "Comparing a fast implementation against a slow, obviously correct one on the same inputs."],
    ["snapshot rot", "Snapshots updated blindly until they no longer check anything."],
    ["warm-up", "Runs discarded before measuring, so the JIT has compiled the hot code."],
  ],
  explain: "Explain to a friend why a test suite with 100% coverage can still miss bugs, and how you'd prove a speed-up claim honestly.",
};
