export default {
  id: "tricks",
  n: 49,
  part: "I",
  title: "Tricks nobody tells you",
  hook: "Small moves, each worth an afternoon you'd otherwise lose. CSS, JS, DevTools, git, SQL, design and shipping.",
  minutes: 75,
  levels: ["use", "understand"],
  sections: [
    {
      title: "CSS that deletes JavaScript",
      beats: [
        { t: "say", x: "Every trick here passed one test: you'd otherwise learn it after a bug report, not from a tutorial. The ones already covered elsewhere (stacking contexts, `text-wrap`, `:user-invalid`, `inert`) are left out on purpose. These are the gaps between them." },
        {
          t: "predict",
          lang: "css",
          src: ".drawer {\n  position: fixed; inset: 0 auto 0 0; width: 320px;\n  overflow-y: auto;\n}\n/* the page behind it is long */",
          q: "The user scrolls the drawer's list to the bottom and keeps scrolling. What moves?",
          options: ["Nothing, the drawer stops", "The page behind the drawer starts scrolling", "The drawer bounces and stops", "The drawer scrolls past its end"],
          answer: 1,
          why: "**Scroll chaining**: once a scroller hits its edge, leftover scroll goes to the next scroller up, the page. People fix it with `body { overflow: hidden }` and JS. `overscroll-behavior: contain` on the drawer stops the hand-off in one line.",
        },
        {
          t: "play",
          mode: "html",
          title: "scroll chaining, accent-color",
          html: "<label><input type=\"checkbox\" id=\"c\"> overscroll-behavior: contain</label>\n<div class=\"panel\" id=\"p\"></div>\n<div class=\"page\"></div>",
          css: ":root { accent-color: #d49a3a; }\nbody { font-family: system-ui; padding: 12px; }\n.panel { height: 160px; width: 220px; overflow-y: auto; border: 1px solid #888; margin: 10px 0; }\n.panel.contain { overscroll-behavior: contain; }\n.panel p { margin: 0; padding: 6px 10px; border-bottom: 1px solid #8883; }\n.page { height: 2000px; background: repeating-linear-gradient(#8881 0 40px, transparent 40px 80px); }",
          js: "const p = document.getElementById('p');\np.innerHTML = Array.from({ length: 20 }, (_, i) => '<p>item ' + (i + 1) + '</p>').join('');\ndocument.getElementById('c').onchange = (e) => p.classList.toggle('contain', e.target.checked);",
          task: "Wheel past the end of the list: the page scrolls. Tick the box and retry. The orange checkbox is `accent-color` on `:root`: one line themes every checkbox, radio, range and progress.",
        },
        {
          t: "code",
          lang: "css",
          src: "/* anchors and scrollIntoView() land under a sticky header */\nhtml { scroll-padding-top: 72px; }   /* every jump in this scroller */\nh2   { scroll-margin-top: 1rem; }    /* extra room for one kind of target */\n\n/* a phone's notch and home bar, with <meta name=\"viewport\"\n   content=\"width=device-width, initial-scale=1, viewport-fit=cover\"> */\n.bottom-bar {\n  padding-bottom: max(12px, env(safe-area-inset-bottom));\n}",
          mark: [2, 3, 9],
          note: "Both are honoured by `#hash` links and `scrollIntoView()`. `env()` returns 0 where there's no notch, so `max()` keeps your normal padding.",
        },
        {
          t: "predict",
          lang: "css",
          src: "/* open a modal: stop the page scrolling behind it */\nhtml:has(dialog[open]) { overflow: hidden; }",
          q: "A tester on Windows says \"the whole page twitches sideways when the modal opens\". You're on a Mac and see nothing. Why?",
          options: ["A Windows font rendering bug", "The scrollbar disappears and the content gets ~15px wider", "The dialog's backdrop shifts the page", "`:has()` is slow on Windows"],
          answer: 1,
          why: "Classic scrollbars take layout space; macOS overlay scrollbars don't, so you never see it. Hide the scrollbar and everything re-centres. `html { scrollbar-gutter: stable }` keeps the space reserved (Baseline since late 2024).",
        },
        {
          t: "pitfall",
          h: "Your 16px icon button is a 16px target",
          x: "Small icon buttons are missed on touch, and WCAG 2.2 asks for at least 24x24 CSS px. Don't grow the icon: give the button `position: relative` and a `::before { content: ''; position: absolute; inset: -10px; }`. The pseudo-element is part of the button, so it takes the clicks.",
        },
      ],
    },
    {
      title: "Popovers: menus with zero JavaScript",
      beats: [
        { t: "say", x: "The `popover` attribute gives any element the top layer, Escape and click-outside to close (**light dismiss**), and one-open-at-a-time. A button with `popovertarget` toggles it. No listeners, no z-index, no focus code. Baseline in every current browser." },
        {
          t: "play",
          mode: "html",
          title: "a menu and a toast, no handlers",
          html: "<button popovertarget=\"menu\">Menu</button>\n<button popovertarget=\"help\">Help</button>\n<button id=\"save\">Save</button>\n\n<div id=\"menu\" popover>\n  <button>Rename</button><button>Duplicate</button><button>Delete</button>\n</div>\n<div id=\"help\" popover>Opening me closed the menu.</div>\n<div id=\"toast\" popover=\"manual\">Saved</div>",
          css: "body { font-family: system-ui; padding: 16px; }\n#menu { display: none; }\n#menu:popover-open { display: grid; gap: 4px; padding: 8px; border-radius: 8px; }\n#toast { inset: auto 16px 16px auto; margin: 0; padding: 10px 14px;\n  border-radius: 8px; background: #222; color: #fff; border: 0; }",
          js: "const toast = document.getElementById('toast');\ndocument.getElementById('save').onclick = () => {\n  toast.showPopover();\n  setTimeout(() => toast.hidePopover(), 1500);\n};\ndocument.getElementById('menu').addEventListener('toggle', (e) => console.log('menu', e.newState));",
          task: "Open Menu: it lands mid-screen. Then Help: the menu closes. Press Escape, click outside. Then Save twice fast: a `manual` popover never light-dismisses, so you own closing it.",
        },
        {
          t: "table",
          head: ["", "`popover` (auto)", "`popover=\"manual\"`", "`<dialog>` + `showModal()`"],
          rows: [
            ["Top layer", "yes", "yes", "yes"],
            ["Esc / click outside closes", "both", "neither", "Esc only"],
            ["Closes open auto popovers", "yes, except its ancestors", "no", "yes"],
            ["Page behind", "stays interactive", "stays interactive", "inert"],
            ["Use for", "menus, pickers, tooltips you click", "toasts, live status", "anything that must be answered"],
          ],
        },
        {
          t: "pitfall",
          h: "A popover appears in the middle of the screen",
          x: "The UA stylesheet gives `[popover]` `position: fixed; inset: 0; margin: auto`: centred on the viewport, not next to its button, wherever it sits in the DOM. Set `inset` and `margin` yourself, or position it from the button's rect in the `toggle` event.",
        },
        {
          t: "quiz",
          q: "A `<dialog>` is open with `showModal()`. Your code then calls `showPopover()` on a `manual` toast. Where does the toast paint?",
          options: ["Behind the dialog's backdrop", "Above the dialog, but its buttons can't be clicked", "It can't open while a modal is up", "Wherever its z-index puts it"],
          answer: 1,
          why: "The top layer is a stack, last in on top, so the toast paints above the modal with no z-index. But a modal makes everything outside it inert, toast included. Fine for 'Saved'; an Undo button in it is dead until the modal closes.",
        },
      ],
    },
    {
      title: "JavaScript you'd otherwise npm install",
      beats: [
        { t: "say", x: "`Intl` ships with every browser and Node: relative times, lists, ordinals, compact numbers, currencies and date ranges, correct for every locale. Many formatting packages in your bundle re-implement a slice of it, 20 KB at a time." },
        {
          t: "play",
          mode: "js",
          title: "Intl does the formatting",
          js: "const rtf = new Intl.RelativeTimeFormat('en', { numeric: 'auto' });\nconsole.log(rtf.format(-1, 'day'), '|', rtf.format(-3, 'day'), '|', rtf.format(2, 'week'));\n\nconsole.log(new Intl.ListFormat('en').format(['Ada', 'Grace', 'Linus']));\nconsole.log(new Intl.ListFormat('en', { type: 'disjunction' }).format(['card', 'UPI', 'cash']));\n\nconst pr = new Intl.PluralRules('en', { type: 'ordinal' });\nconst suffix = { one: 'st', two: 'nd', few: 'rd', other: 'th' };\nconsole.log([1, 2, 3, 4, 11, 12, 21, 102].map((n) => n + suffix[pr.select(n)]).join(' '));\n\nconst compact = (loc) => new Intl.NumberFormat(loc, { notation: 'compact' }).format(1234567);\nconsole.log(compact('en'), compact('en-IN'));\nconsole.log(new Intl.NumberFormat('de', { style: 'currency', currency: 'EUR' }).format(1234.5));\n\nconst a = new Date(Date.UTC(2026, 9, 5)), b = new Date(Date.UTC(2026, 9, 9));\nconsole.log(new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', timeZone: 'UTC' }).formatRange(a, b));\nconsole.log('your zone:', Intl.DateTimeFormat().resolvedOptions().timeZone);",
          task: "Switch the ListFormat and NumberFormat locales to 'de', 'ja' and 'hi'. Then notice `11th` and `12th`: the ordinal rules handle the teens you'd have got wrong by hand.",
        },
        {
          t: "pitfall",
          h: "Build formatters once, not per row",
          x: "`new Intl.NumberFormat(...)` loads locale data and resolves options. `toLocaleString(locale, options)` can redo that work on every call. In a 5,000-row table that's measurable. Create the formatter once at module level and call `.format()` in the loop.",
        },
        {
          t: "predict",
          lang: "js",
          src: "const orders = [\n  { id: 1, status: 'paid' }, { id: 2, status: 'refunded' }, { id: 3, status: 'paid' },\n];\nconst byStatus = Object.groupBy(orders, (o) => o.status);\nconsole.log(byStatus.hasOwnProperty('paid'));",
          q: "What happens?",
          options: ["true", "false", "TypeError: hasOwnProperty is not a function", "undefined"],
          answer: 2,
          why: "`Object.groupBy` returns a **null-prototype** object, so a group named `toString` can't collide with anything inherited. The price: no inherited methods. Use `Object.hasOwn(byStatus, 'paid')` or `'paid' in byStatus`. `Map.groupBy` keys by any value.",
        },
        {
          t: "compare",
          a: { label: "re-render never happens", lang: "js", src: "const [items, setItems] = useState(list);\n\nfunction sortByPrice() {\n  setItems(items.sort((a, b) => a.price - b.price));\n}" },
          b: { label: "a new array, as React expects", lang: "js", src: "const [items, setItems] = useState(list);\n\nfunction sortByPrice() {\n  setItems(items.toSorted((a, b) => a.price - b.price));\n}" },
          x: "`sort()` reorders in place and returns the same array, so `Object.is` says nothing changed and React skips the update. `toSorted`, `toReversed`, `toSpliced` and `with(i, v)` return copies.",
        },
        {
          t: "code",
          lang: "js",
          src: "const had = new Set(['read', 'write', 'admin']);\nconst has = new Set(['read', 'write', 'billing']);\n\nhas.difference(had);          // Set { 'billing' }   granted\nhad.difference(has);          // Set { 'admin' }     revoked\nhad.intersection(has);        // Set { 'read', 'write' }\nhad.symmetricDifference(has); // Set { 'admin', 'billing' }   anything changed\nhad.isSubsetOf(has);          // false\n\n// errors that keep their history\ntry { await fetch(url); }\ncatch (e) { throw new Error('could not load cart ' + id, { cause: e }); }",
          mark: [4, 5, 12],
          note: "Set methods are Baseline since mid-2024. `cause` keeps the low-level error under your readable one; Node prints the whole chain as `[cause]` when it crashes.",
        },
      ],
    },
    {
      title: "Tabs, locks and secure contexts",
      beats: [
        {
          t: "predict",
          lang: "js",
          src: "const a = new BroadcastChannel('auth');\nconst b = new BroadcastChannel('auth');\na.onmessage = (e) => console.log('a got', e.data);\nb.onmessage = (e) => console.log('b got', e.data);\na.postMessage('logout');\nconsole.log('sent');",
          q: "Same page. What prints?",
          options: ["a got logout, b got logout, sent", "sent, b got logout", "sent, a got logout, b got logout", "sent"],
          answer: 1,
          why: "A channel never hears its own posts, but every other channel with that name does: other tabs, iframes, workers, or another object in this very page. Delivery is async, so `sent` comes first. One line logs out every tab.",
        },
        { t: "say", h: "Five tabs, one refresh", x: "Five tabs see the token expire and all five call `/refresh`. With rotating refresh tokens, four send a token that was just rotated away, and reuse detection may kill the session. The **Web Locks API** makes the refresh a critical section across tabs." },
        {
          t: "code",
          lang: "js",
          src: "async function accessToken() {\n  return navigator.locks.request('token-refresh', async () => {\n    // waited for the lock? another tab may have refreshed already\n    const t = readStoredToken();\n    if (t && t.exp > Date.now() + 30_000) return t.value;\n\n    const fresh = await refreshToken();   // only one tab gets here\n    storeToken(fresh);\n    return fresh.value;\n  });\n}",
          mark: [2, 5],
          note: "The lock is held until the callback's promise settles, and `request` resolves with its return value. Same-origin, every tab and worker, released automatically if a tab dies.",
        },
        {
          t: "pitfall",
          h: "It works on localhost and breaks on your phone",
          x: "`crypto.randomUUID`, Web Locks, the clipboard API and service workers exist only in **secure contexts**. `localhost` counts; `http://192.168.1.20:5173` doesn't, so on a phone they're undefined and the app white-screens. Check `isSecureContext`, or serve dev over HTTPS.",
        },
        {
          t: "quiz",
          q: "You need a random id on a page that might be served over plain http. Which still works there?",
          options: ["`crypto.randomUUID()`", "`crypto.getRandomValues(new Uint8Array(16))`", "`navigator.locks.request`", "`navigator.clipboard.writeText`"],
          answer: 1,
          why: "`getRandomValues` is available in any context; `randomUUID` and the other two are secure-context only. `Math.random` is not a fallback for ids that must not collide or be guessed.",
        },
      ],
    },
    {
      title: "DevTools moves",
      beats: [
        {
          t: "table",
          head: ["Problem", "Move (Chrome DevTools)"],
          rows: [
            ["A dropdown vanishes when you click into DevTools", "Rendering > **Emulate a focused page**; the page never sees the blur"],
            ["Does the layout survive long German copy?", "Console: `document.designMode = 'on'`, then type straight into the page"],
            ["A clean screenshot of one component", "Select it in Elements, Ctrl/Cmd+Shift+P, **Capture node screenshot**"],
            ["Which requests are heavy, or failing?", "Network filter: `larger-than:100k`, `status-code:500`, `domain:*.cdn.com`"],
            ["Dark mode and reduced motion without OS settings", "Rendering > emulate `prefers-color-scheme`, `prefers-reduced-motion`"],
            ["A logged object you want to poke at", "Right-click it > **Store as global variable**, then use `temp1`"],
          ],
        },
        {
          t: "play",
          mode: "html",
          title: "designMode: edit the page itself",
          html: "<button id=\"t\">designMode: off</button>\n<article class=\"card\">\n  <h2>Pro plan</h2>\n  <p class=\"price\">$12 / month</p>\n  <button class=\"cta\">Start trial</button>\n</article>",
          css: "body { font-family: system-ui; padding: 16px; }\n.card { width: 220px; padding: 16px; border: 1px solid #8886; border-radius: 12px; }\n.card h2 { margin: 0 0 4px; }\n.price { margin: 0 0 12px; color: #777; }\n.cta { width: 100%; padding: 10px; white-space: nowrap; }",
          js: "const t = document.getElementById('t');\nt.onclick = () => {\n  document.designMode = document.designMode === 'on' ? 'off' : 'on';\n  t.textContent = 'designMode: ' + document.designMode;\n};",
          task: "Turn it on, click into the heading and type `Unternehmenspaketverwaltung`. One long German word bursts the card. Fix: `overflow-wrap: anywhere`, found before the translators did.",
        },
        {
          t: "pitfall",
          h: "Cache disabled only while DevTools is open",
          x: "**Disable cache** in Network applies only while DevTools is open. Close it and you're testing a different site: cached JS and CSS. It never bypassed the service worker: that's a switch in Application. For bugs that 'only happen to users', reproduce with DevTools closed, or in a fresh profile.",
        },
        {
          t: "quiz",
          q: "An autocomplete list closes as soon as you right-click it to inspect. Emulating a focused page didn't help. What's the next move?",
          options: ["Inspect faster", "Right-click the list's parent in Elements > Break on > subtree modifications", "Disable JavaScript", "Use Firefox"],
          answer: 1,
          why: "A **DOM breakpoint** pauses on the line that removes the list, with the handler that fired it on the call stack. Now you know what closes it, and a breakpoint just before that line freezes it open.",
        },
      ],
    },
    {
      title: "git and the terminal",
      beats: [
        { t: "say", h: "Two branches, two folders", x: "A hotfix lands mid-feature. Stash, switch, reinstall, rebuild, switch back, pop, pray. Or: `git worktree` checks out another branch into a second folder that shares the same `.git`. Both stay open in your editor, both servers can run." },
        {
          t: "code",
          lang: "bash",
          src: "git worktree add ../app-hotfix -b hotfix/login origin/main\ncd ../app-hotfix && npm ci          # node_modules is per folder\n# fix, commit, push from here; your feature folder is untouched\n\ngit worktree list\ngit worktree remove ../app-hotfix    # when the PR merges",
          mark: [1, 2],
          note: "One rule: a branch can be checked out in only one worktree at a time; git refuses the second. Commits, stashes and the reflog are shared, because there is one repository.",
        },
        {
          t: "predict",
          lang: "bash",
          src: "# commit one:    adds    const LIMIT = 50;   at the top of f.js\n# commit move:   moves   that line to the bottom, unchanged\n# commit change: edits   it to   const LIMIT = 80;\n\ngit log -S LIMIT --oneline",
          q: "Which commits does `-S` list?",
          options: ["all three", "one and change", "only one", "move and change"],
          answer: 2,
          why: "`-S` (the **pickaxe**) lists commits where the *count* of the string changed. Moving or editing that line leaves one `LIMIT`. `-G LIMIT` matches any added or removed line containing it and lists all three. Use `-S` for 'when was this introduced or deleted'.",
        },
        {
          t: "code",
          lang: "bash",
          src: "# the history of one function, not one file\ngit log -L :applyDiscount:src/cart.js\n\n# after a rebase: did my commits change, or only move?\ngit range-diff main ORIG_HEAD HEAD\n# 1:  1744e19 = 1:  26b39d6 feat a      (= same patch)\n# 2:  fa9aeec ! 2:  d8cb294 feat b      (! changed, diff follows)\n# -:  ------- > 3:  0c5eb31 fix         (> new)",
          mark: [2, 5],
          note: "`-L` finds the function in today's file, traces that line range back, and prints only its diff per commit. `range-diff` is how you review a force-pushed PR without rereading it.",
        },
        {
          t: "table",
          head: ["`git config --global`", "What it stops"],
          rows: [
            ["`push.autoSetupRemote true`", "The `--set-upstream origin` error on every new branch's first push (git 2.37+)"],
            ["`fetch.prune true`", "Remote branches deleted on GitHub living forever in your `git branch -r`"],
            ["`branch.sort -committerdate`", "Scrolling through 80 old branches; recent ones list first"],
            ["`diff.colorMoved zebra`", "Reviewing moved code as delete + add; moved blocks get their own colour"],
            ["`commit.verbose true`", "Writing a message blind; the diff shows under it in the editor"],
          ],
        },
        {
          t: "steps",
          h: "Terminal moves that compound",
          items: [
            "**Ctrl+R** searches your history as you type; Ctrl+R again for older matches. Works in bash, zsh and PowerShell.",
            "**Alt+.** (bash, zsh) pastes the last argument of the previous command: `mkdir -p a/b/c` then `cd` Alt+.",
            "Port 3000 already in use: `lsof -i :3000` on macOS and Linux, `netstat -ano | findstr :3000` on Windows, then kill that PID.",
            "`git grep -n 'useCart('` searches only tracked files, so `node_modules` and `dist` never flood the results.",
          ],
        },
        {
          t: "pitfall",
          h: "A worktree is not a clean copy",
          x: "A new worktree has none of your ignored files: no `node_modules`, no `.env`, no build cache. The first run fails with missing env vars, and it looks like the hotfix branch is broken. Copy `.env` across and install before you judge it.",
        },
      ],
    },
    {
      title: "Backend moves",
      beats: [
        {
          t: "code",
          lang: "js",
          file: "server.js",
          src: "app.get('/api/orders', async (req, res) => {\n  const t0 = performance.now();\n  const rows = await db.query('SELECT ... LIMIT 50');\n  const t1 = performance.now();\n  const body = JSON.stringify(rows);\n  const t2 = performance.now();\n\n  res.set('Server-Timing',\n    `db;dur=${(t1 - t0).toFixed(1)}, json;dur=${(t2 - t1).toFixed(1)}`);\n  res.type('json').send(body);\n});",
          mark: [8, 9],
          note: "DevTools draws these as bars in the request's **Timing** tab, under the browser's own numbers. 'Waiting for server: 900 ms' becomes 'db: 870 ms' with no log diving.",
        },
        {
          t: "pitfall",
          h: "Server-Timing is public",
          x: "Every visitor can read the header, and attackers love timing: `auth;dur=` that differs for real and fake usernames tells them which accounts exist. Send detailed timings only to staff, or strip the header at the edge for public traffic.",
        },
        {
          t: "code",
          lang: "sql",
          src: "-- a job queue in Postgres: many workers, no double-processing\nUPDATE jobs SET status = 'running', started_at = now()\nWHERE id = (\n  SELECT id FROM jobs\n  WHERE status = 'queued'\n  ORDER BY id\n  LIMIT 1\n  FOR UPDATE SKIP LOCKED\n)\nRETURNING id, payload;",
          mark: [8],
          note: "Without `SKIP LOCKED`, every worker waits on the same first row. With it, each takes the next row nobody holds. Before you reach for Redis or a broker, this handles a lot of traffic.",
        },
        {
          t: "predict",
          lang: "sql",
          src: "CREATE UNIQUE INDEX users_email_live\n  ON users (lower(email)) WHERE deleted_at IS NULL;\n\n-- a soft-deleted row: ('ada@x.io', deleted_at = '2026-01-01')\nINSERT INTO users (email) VALUES ('Ada@x.io');   -- 1\nINSERT INTO users (email) VALUES ('ADA@x.io');   -- 2",
          q: "Which inserts succeed?",
          options: ["Neither", "Only 1", "Both", "Only 2"],
          answer: 1,
          why: "A **partial** index only covers rows matching its `WHERE`, so the deleted row doesn't count and Ada can sign up again. Insert 2 collides with insert 1 on `lower(email)`. One index enforces 'unique among live users, ignoring case'.",
        },
        {
          t: "predict",
          lang: "sql",
          src: "BEGIN;\nINSERT INTO audit (at) VALUES (now());\nSELECT pg_sleep(2);\nINSERT INTO audit (at) VALUES (now());\nCOMMIT;",
          q: "In Postgres, how far apart are the two `at` values?",
          options: ["About 2 seconds", "Exactly 0", "A few microseconds", "It depends on the server clock"],
          answer: 1,
          why: "`now()` is the time the **transaction** started, constant until commit, so rows written together sort together. For the wall clock inside a long transaction, use `clock_timestamp()`. A two-hour batch job stamping every row with its start time is this.",
        },
        {
          t: "quiz",
          q: "A `UNIQUE (email)` column. Two users sign up with no email (NULL). What does Postgres do?",
          options: ["Rejects the second", "Accepts both: NULLs are not equal to each other", "Converts NULL to ''", "Rejects both"],
          answer: 1,
          why: "Standard SQL treats NULLs as distinct, so a unique column holds any number of them. If you want one at most, Postgres 15+ has `UNIQUE NULLS NOT DISTINCT`; otherwise a unique index on `((email IS NULL)) WHERE email IS NULL`.",
        },
      ],
    },
    {
      title: "Design details that read as quality",
      beats: [
        { t: "say", x: "Users never name these. They just say one product feels solid and another feels cheap. Each is a line or two of CSS, and each fixes something the eye catches before the brain does." },
        {
          t: "play",
          mode: "html",
          title: "edges, underlines, hit areas",
          html: "<label><input type=\"checkbox\" id=\"on\" checked> details on</label>\n<div id=\"demo\" class=\"on\">\n  <div class=\"thumb\"></div>\n  <p>Read the <a href=\"#\">full changelog</a> or <a href=\"#\">typography guide</a>.</p>\n  <button class=\"icon\" aria-label=\"Close\">x</button>\n</div>",
          css: "body { font: 17px/1.5 system-ui; padding: 16px; background: #fff; color: #222; }\n#demo { display: grid; gap: 12px; justify-items: start; }\n.thumb { width: 160px; height: 90px; border-radius: 10px;\n  background: linear-gradient(#fff 0 60%, #f4f4f4 60%); }\na { color: #1a5fb4; }\n.icon { position: relative; width: 16px; height: 16px; padding: 0; font-size: 11px; line-height: 1; }\n\n.on .thumb { outline: 1px solid rgb(0 0 0 / .1); outline-offset: -1px; }\n.on a { text-underline-offset: .2em; text-decoration-thickness: 1px; }\n.on a:hover { text-decoration-thickness: 2px; }\n.on .icon::before { content: ''; position: absolute; inset: -10px; outline: 1px dashed #d49a3a; }",
          js: "document.getElementById('on').onchange = (e) => document.getElementById('demo').classList.toggle('on', e.target.checked);",
          task: "Toggle it. The inset translucent outline gives a white image an edge on any background; the underline clears descenders; the dashed box is the real hit area.",
        },
        {
          t: "compare",
          a: { label: "the badge squashes", lang: "css", src: ".row { display: flex; gap: 8px; }\n.row .badge { width: 24px; height: 24px; }" },
          b: { label: "fixed parts don't shrink", lang: "css", src: ".row { display: flex; gap: 8px; }\n.row .badge { width: 24px; height: 24px;\n  flex: none; }\n.row .label { min-width: 0; }" },
          x: "Flex items shrink by default, and `width` is only a starting size. A long label squeezes the badge thinner. `flex: none` locks fixed-size parts; `min-width: 0` lets the text shrink and ellipsis instead.",
        },
        {
          t: "pitfall",
          h: "Scrollers cut focus rings in half",
          x: "A carousel or tab bar with `overflow: auto` clips everything outside its padding box, so the first card's focus ring is sliced off and keyboard users lose their place. Give the scroller a few px of padding, or draw the ring inside with `outline-offset: -3px`.",
        },
      ],
    },
    {
      title: "Shipping: flags and kill switches",
      beats: [
        { t: "say", h: "Deploy is not release", x: "A **deploy** puts code on servers. A **release** turns it on for people. Feature flags split the two: merge daily, ship dark, turn on for staff, then 1%, then everyone. Rollback becomes a toggle, not a 10-minute redeploy." },
        {
          t: "play",
          mode: "js",
          title: "percentage rollout by hashing",
          js: "// FNV-1a: tiny, fast, stable across machines and languages\nfunction hash(s) {\n  let h = 0x811c9dc5;\n  for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 0x01000193); }\n  return h >>> 0;\n}\nconst bucket = (flag, user) => hash(flag + ':' + user) % 100;   // 0..99, same every time\nconst enabled = (flag, user, pct) => bucket(flag, user) < pct;\n\nconst users = Array.from({ length: 10000 }, (_, i) => 'user-' + i);\nconst cohort = (flag, pct) => new Set(users.filter((u) => enabled(flag, u, pct)));\n\nconst checkout10 = cohort('new-checkout', 10);\nconst dark10 = cohort('dark-mode', 10);\nconsole.log('new-checkout', checkout10.size, 'dark-mode', dark10.size);\nconsole.log('in both:', checkout10.intersection(dark10).size, '(about 1% if independent)');\nconsole.log('10% cohort kept at 20%:', checkout10.isSubsetOf(cohort('new-checkout', 20)));",
          task: "Drop `flag + ':'` from `bucket`: the same 10% of users now get every experiment, and every bug. Then swap the hash for `Math.random()` and watch cohorts reshuffle per call.",
        },
        {
          t: "predict",
          lang: "js",
          src: "// rollout went 10% -> 20%\nconst on = hash('new-checkout:' + userId) % 100 < pct;",
          q: "A user who had the new checkout at 10%. What do they see at 20%?",
          options: ["50% chance of keeping it", "Still the new checkout", "The old one, re-rolled", "It depends on the session"],
          answer: 1,
          why: "Their bucket is fixed by the hash, say 7. `7 < 10` and `7 < 20` are both true. Raising the percentage only adds users; nobody flips back and forth, which would look like a bug to them and wreck your metrics.",
        },
        {
          t: "code",
          lang: "js",
          src: "const DEFAULTS = {\n  'new-checkout': false,     // release flag: off unless told otherwise\n  'recommendations': true,   // kill switch: on, flip off when it melts\n};\nlet flags = DEFAULTS, lastGood = null;\n\nasync function refreshFlags() {\n  try {\n    const res = await fetch('/flags', { signal: AbortSignal.timeout(1000) });\n    if (!res.ok) throw new Error('flags ' + res.status);\n    flags = lastGood = { ...DEFAULTS, ...(await res.json()) };\n  } catch {\n    flags = lastGood ?? DEFAULTS;   // never block a page on the flag service\n  }\n}\nsetInterval(refreshFlags, 30_000);",
          mark: [3, 13],
          note: "A **kill switch** is a flag that defaults on and exists to be turned off: a slow third-party widget, an expensive query, a new code path. It must work without a deploy and without the flag service.",
        },
        {
          t: "quiz",
          q: "Your app has 12 boolean flags still in the code. How many configurations can production be in?",
          options: ["12", "24", "144", "4096"],
          answer: 3,
          why: "2^12. Nobody tests 4096 combinations, so stale flags are untested code paths waiting for someone to flip them. Give every release flag an owner and a removal date, and delete it when it hits 100%.",
        },
        {
          t: "pitfall",
          h: "A kill switch nobody has pulled doesn't work",
          x: "The off path rots: it throws on a missing import, or the page relies on markup only the feature renders. Flip every kill switch in staging on a schedule, like a fire drill. The night you need it is the wrong time to find out.",
        },
        {
          t: "mission",
          h: "A flag client in 80 lines",
          x: "Write `flags.js` for a real app: hashed percentage rollouts per flag, an allow-list for staff, defaults that are safe when the flag endpoint is down, a kill switch for one expensive feature, and a script that lists flags at 0% or 100% for more than 30 days.",
          hint: "Store flags as `{ pct, allow: [], killed, createdAt }`. `killed` wins over everything. For the stale report, the oldest commit in `git log -S 'flagName'` is the one that added the flag.",
        },
      ],
    },
  ],
  nobodyTells: [
    "`overscroll-behavior: contain` on every drawer, modal body and chat panel. Nobody notices it; everybody notices when it's missing.",
    "Test on Windows, or turn on 'always show scrollbars' on macOS. A whole class of layout-shift and overflow bugs hides behind overlay scrollbars.",
    "`designMode = 'on'` plus the longest real string in your data is the cheapest overflow and i18n test there is.",
    "`localhost` is a secure context and your LAN IP isn't. Test phone builds over HTTPS or expect undefined APIs.",
    "`git log -S` answers 'who deleted this function and why' in seconds. It's the best archaeology tool most people never use.",
    "Put `Server-Timing` on your slowest endpoint today. The first time it says `db;dur=870` you'll add it everywhere.",
    "`now()` in Postgres is frozen for the whole transaction. Great for consistency, surprising for audit logs.",
    "Delete a feature flag the week it reaches 100%. A flag that outlives its launch becomes configuration nobody understands.",
  ],
  glossary: [
    ["scroll chaining", "Leftover scroll passing from a scroller at its edge to the next scroller up, usually the page."],
    ["light dismiss", "Closing a popover by clicking outside it or pressing Escape, built into `popover=\"auto\"`."],
    ["top layer", "A stack above all z-index where modal dialogs and popovers paint, last opened on top."],
    ["null-prototype object", "An object with no `Object.prototype`, so it has no inherited methods or keys."],
    ["secure context", "HTTPS or localhost. Many powerful APIs exist only there."],
    ["Web Locks", "A browser API for named locks shared by every tab and worker of an origin."],
    ["git worktree", "An extra working folder attached to the same repository, on a different branch."],
    ["pickaxe", "`git log -S`: commits where the number of occurrences of a string changed."],
    ["Server-Timing", "A response header with named server durations that DevTools draws in the Timing tab."],
    ["SKIP LOCKED", "A row-locking option that skips rows other transactions hold, so queue workers don't wait."],
    ["partial index", "An index over only the rows matching a WHERE clause."],
    ["kill switch", "A flag that defaults on and exists to turn a feature off at runtime, without a deploy."],
  ],
  explain: "Explain to a friend why hashing `flag + userId` beats `Math.random()` for a percentage rollout, and what goes wrong if you leave the flag name out of the hash.",
};
