/* The course, in order. Each entry is one module in this folder. */

export const parts = {
  A: { title: "How the web actually works", blurb: "What happens between a keystroke in the address bar and pixels on glass." },
  B: { title: "The three languages", blurb: "HTML, CSS and JavaScript, at the depth the engines see them." },
  C: { title: "Tools of the trade", blurb: "Node, bundlers, git, CI and the debugger, from the inside." },
  D: { title: "Frameworks", blurb: "Build React yourself, then use it, Next.js and Vue like you wrote them." },
  E: { title: "Backend and full stack", blurb: "Servers, real-time, databases, auth, shipping. The MERN stack and beyond." },
  F: { title: "Motion and 3D", blurb: "Animation, canvas, WebGL, shaders and a million things at 60 fps." },
  G: { title: "Design", blurb: "The eye: hierarchy, type, colour, motion, systems, and honest testing." },
  H: { title: "Case studies", blurb: "Four real builds, taken apart: how they work and why they're built that way." },
  I: { title: "Reference", blurb: "Tricks, interviews and projects to prove it all." },
};

export const chapters = [
  { n: 0, part: "A", id: "start-here", title: "Start here" },
  { n: 1, part: "A", id: "url-to-response", title: "What happens when you open a URL" },
  { n: 2, part: "A", id: "rendering-pipeline", title: "The rendering pipeline" },
  { n: 3, part: "A", id: "browser-and-v8", title: "Inside the browser and V8" },
  { n: 4, part: "B", id: "html", title: "HTML and accessibility" },
  { n: 5, part: "B", id: "css-cascade", title: "CSS I: the cascade and the box" },
  { n: 6, part: "B", id: "css-layout", title: "CSS II: layout" },
  { n: 7, part: "B", id: "css-modern", title: "CSS III: responsive, tokens and motion" },
  { n: 8, part: "B", id: "js-core", title: "JavaScript I: the real parts" },
  { n: 9, part: "B", id: "js-async", title: "JavaScript II: async and the event loop" },
  { n: 10, part: "B", id: "dom-apis", title: "The DOM and browser APIs" },
  { n: 11, part: "B", id: "typescript", title: "TypeScript for real" },
  { n: 12, part: "C", id: "node-npm", title: "Node, npm and modules" },
  { n: 13, part: "C", id: "bundlers", title: "Bundlers and Vite" },
  { n: 14, part: "C", id: "git", title: "Git for real" },
  { n: 15, part: "C", id: "github-ci", title: "GitHub and CI" },
  { n: 16, part: "C", id: "devtools", title: "DevTools, panel by panel" },
  { n: 17, part: "C", id: "debugging", title: "Debugging like a pro" },
  { n: 18, part: "D", id: "react-from-scratch", title: "React from scratch" },
  { n: 19, part: "D", id: "react-for-real", title: "React for real" },
  { n: 20, part: "D", id: "nextjs", title: "Next.js and rendering strategies" },
  { n: 21, part: "D", id: "vue-reactivity", title: "Vue and reactivity" },
  { n: 22, part: "E", id: "servers-express", title: "HTTP servers and Express" },
  { n: 23, part: "E", id: "apis", title: "Designing APIs" },
  { n: 24, part: "E", id: "api-styles", title: "API styles: REST, GraphQL, gRPC, SOAP and more" },
  { n: 25, part: "E", id: "realtime", title: "Real-time: SSE and WebSockets" },
  { n: 26, part: "E", id: "databases", title: "Databases" },
  { n: 27, part: "E", id: "auth-security", title: "Auth and security" },
  { n: 28, part: "E", id: "finding-vulns", title: "Finding vulnerabilities" },
  { n: 29, part: "E", id: "shipping", title: "Shipping: Docker, hosting, observability" },
  { n: 30, part: "E", id: "mern-capstone", title: "The MERN capstone" },
  { n: 31, part: "F", id: "animation", title: "Animation craft" },
  { n: 32, part: "F", id: "canvas", title: "Canvas 2D" },
  { n: 33, part: "F", id: "webgl", title: "WebGL from zero" },
  { n: 34, part: "F", id: "threejs", title: "Three.js" },
  { n: 35, part: "F", id: "shaders", title: "Shaders" },
  { n: 36, part: "F", id: "million-things", title: "Drawing a million things" },
  { n: 37, part: "F", id: "performance", title: "Performance and robustness" },
  { n: 38, part: "G", id: "seeing", title: "Seeing like a designer" },
  { n: 39, part: "G", id: "typography", title: "Typography" },
  { n: 40, part: "G", id: "colour", title: "Colour" },
  { n: 41, part: "G", id: "motion-design", title: "Motion and interaction design" },
  { n: 42, part: "G", id: "design-systems", title: "Design systems and tokens" },
  { n: 43, part: "G", id: "not-ai-made", title: "Writing and design that don't look AI-made" },
  { n: 44, part: "G", id: "testing", title: "Testing and honesty" },
  { n: 45, part: "H", id: "case-valence", title: "Case study: Valence" },
  { n: 46, part: "H", id: "case-railflow", title: "Case study: RailFlow" },
  { n: 47, part: "H", id: "case-portfolio", title: "Case study: the portfolio" },
  { n: 48, part: "H", id: "case-github", title: "Case study: the GitHub profile" },
  { n: 49, part: "I", id: "tricks", title: "Tricks nobody tells you" },
  { n: 50, part: "I", id: "interviews", title: "Interview questions, answered" },
  { n: 51, part: "I", id: "capstones", title: "Capstones" },
];

export const file = (c) => `./${String(c.n).padStart(2, "0")}-${c.id}.js`;
